---
title: "Tip_cells"
output: html_document
date: "2025-10-08"
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo                  = FALSE
                      ,warning              = FALSE
                      ,message              = FALSE
                      ,error                = TRUE
                      ,dev                  = c('png','pdf')
                      ,pdf.options(encoding = "ISOLatin9.enc", useKerning=FALSE, useDingbats=FALSE))
.libPaths("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Rloading/4.4/")

```


A report by **Elyas.Mohammadi**

Here I try to prepare the scATACseq data from three sources. 1- Our in house generated data (Heart and brain) 2- Sten's data (Brain) 3- AmeenM data (Heart)


```{r libraries}
# library(data.table)
library(harmony)


library(ggplot2)
library(ggrepel)
library(ggpubr)
library(patchwork)
# library(clusterProfiler)
# library(org.Hs.eg.db)
library(AnnotationHub)
# library(EnsDb.Hsapiens.v86)
library(ggthemes)
library(viridis)
library(dplyr)
library(GenomicRanges)
library(GenomeInfoDb)
library(tidyr)
library(RColorBrewer)
library(scales)
library(gridExtra)
library(pheatmap)

library(ggh4x)
axis <- ggh4x::guide_axis_truncated(
  trunc_lower = unit(0, "npc"),
  trunc_upper = unit(1.5, "cm"))

library(Signac)

# Changing the Seurat version to 5
.libPaths("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Rloading/4.4.Spatial/")
# install.packages('Seurat')
unloadNamespace("Seurat")  
library(Seurat)
.libPaths("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Rloading/4.4")


```


# Tip_cells

```{r Tip_cells,fig.width=15,fig.height=20}
ATAC.all <- readRDS("./ATAC.all.int3_2.splitted.Rds")
RNA.int <- readRDS("./RNA.int_2.splitted.Rds")

ATAC.all$`Tip cells`$Organ_subtypes <- paste0(ATAC.all$`Tip cells`$Organ,"_",ATAC.all$`Tip cells`$newL3_Subtype.multi.pred_2)
RNA.int$`Tip cells`$Organ_subtypes <- paste0(RNA.int$`Tip cells`$Organ,"_",RNA.int$`Tip cells`$newL3_Subtype)

RNA.int$`Tip cells` <- subset(RNA.int$`Tip cells`, Age.PCW !="PCW22")

# meta <- readRDS("./meta.Rds")


# Trying to find DEGs celltypes in RNA and ATAC (ACTIVITY assay) data

###############################################################################################################
################################################ DEGs #######################################################
###############################################################################################################

# DefaultAssay(ATAC.all$`Tip cells`) <- 'Peak.celltype'
# 
# # wilcox is the default option for test.use
# da_peaks.Tip_cells <- FindMarkers(
#   object = ATAC.all$`Tip cells`,
#   ident.1 = "Brain",
#   ident.2 = "Heart",
#   test.use = 'LR',
#   min.pct = 0.05,
#   latent.vars = c('nCount_peaks',"Source"),group.by = "Region"
# )
# 
# save(da_peaks.Tip_cells,file = "./Cross_organ.celltype.degs_Tip_cells.Rdata")
# ATAC.Tip_cells.deg <- FindMarkers(ATAC.all$`Tip cells`,ident.1 = "Brain",ident.2 = "Heart",logfc.threshold = 0.5,test.use = "MAST",latent.vars = "Source2",group.by = "Region",assay = "ACTIVITY")
# RNA.Tip_cells.deg <- FindMarkers(RNA.int$`Tip cells`,ident.1 = "Brain",ident.2 = "Heart",logfc.threshold = 0.5,test.use = "MAST",latent.vars = "Dataset",group.by = "Organ")
# save(ATAC.Tip_cells.deg,RNA.Tip_cells.deg,da_peaks.Tip_cells,file = "./Cross_organ.celltype.degs_Tip_cells.Rdata")

load(file = "./Cross_organ.celltype.degs_Tip_cells.Rdata")


x <- subset(ATAC.Tip_cells.deg, p_val_adj<0.01)
x.up <- x[order(-x$avg_log2FC, -x$p_val_adj),][1:100,]
x.down <- x[order(x$avg_log2FC, -x$p_val_adj),][1:100,]
x.up$Direction <- "Up"
x.down$Direction <- "Down"
tops.atac.Tip_cells <- rbind(x.up,x.down)
tops.atac.Tip_cells$gene <- rownames(tops.atac.Tip_cells)

x <- subset(RNA.Tip_cells.deg, p_val_adj<0.01)
x.up <- x[order(-x$avg_log2FC, -x$p_val_adj),][1:100,]
x.down <- x[order(x$avg_log2FC, -x$p_val_adj),][1:100,]
x.up$Direction <- "Up"
x.down$Direction <- "Down"
tops.rna.Tip_cells <- rbind(x.up,x.down)
tops.rna.Tip_cells$gene <- rownames(tops.rna.Tip_cells)

common.set <- intersect(tops.atac.Tip_cells$gene,tops.rna.Tip_cells$gene)
avg.atac <- AverageExpression(ATAC.all$`Tip cells`,group.by = "Organ",features = common.set[-length(common.set)],assay = "ACTIVITY")$ACTIVITY
avg.rna <- AverageExpression(RNA.int$`Tip cells`,group.by = "Organ",features = common.set[-length(common.set)],assay = "RNA")$RNA

p1 <- pheatmap(
  avg.atac,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  scale = "row",           # optional: scales expression values per gene
  color = colorRampPalette(c("grey40", "white", "purple3"))(100),
  fontsize_row = 12,
  fontsize_col = 12,main = "ATAC_Tip_cells"
)

p2 <- pheatmap(
  avg.rna,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  scale = "row",           # optional: scales expression values per gene
  color = colorRampPalette(c("grey40", "white", "red"))(100),
  fontsize_row = 12,
  fontsize_col = 12,main = "RNA_Tip_cells"
)

pdf("../Results/Manuscript/Figure2/Tip_cells/Tip_cells.degs.RNA.ATAC.pdf",width = 6.5,height = 6)
grid.arrange(grobs = list(p1[[4]],p2[[4]]), ncol = 2)
dev.off()

#_____________________________________________________Age+Organ_____________________________________________________

avg.atac <- AverageExpression(ATAC.all$`Tip cells`,group.by = c("Organ","Age.PCW"),features = common.set[-length(common.set)],assay = "ACTIVITY")$ACTIVITY
avg.rna <- AverageExpression(RNA.int$`Tip cells`,group.by = c("Organ","Age.PCW"),features = common.set[-length(common.set)],assay = "RNA")$RNA

library(dplyr)
library(tidyr)
# library(stringr)
library(readr)   # for parse_number()

col_info_atac <- tibble(col = colnames(avg.atac)) %>%
  separate(col, into = c("Region","Age.PCW"), sep = "_", remove = FALSE) %>%
  mutate(Age.PCW = parse_number(Age.PCW)) %>%   # turns "PCW06" -> 6, "PCW10" -> 10
  arrange(Region, Age.PCW)
avg.atac <- avg.atac[, col_info_atac$col, drop = FALSE]

ann_atac <- col_info_atac %>%
  dplyr::select(Region, Age.PCW) %>%
  as.data.frame()
rownames(ann_atac) <- col_info_atac$col

region_cols <- c(Brain = "#3A86FF", Heart = "#2FBF71")
age_cols   <- colorRampPalette(c("#F5F9FF", "lightblue","blue", "darkblue"))(10)


labels_atac <- as.character(col_info_atac$Age.PCW)

p1 <- pheatmap(
  avg.atac,
  cluster_rows = FALSE, cluster_cols = FALSE, scale = "row",
  color = colorRampPalette(c("grey40","white","purple3"))(100),
  annotation_col = ann_atac,
  annotation_colors = list(Region = region_cols, `Age.PCW` = age_cols),
  fontsize_row = 12, fontsize_col = 12,labels_col = gsub(".*PCW","",colnames(avg.atac)),
  main = "ATAC_Tip_cells"
)

col_info_rna <- tibble(col = colnames(avg.rna)) %>%
  separate(col, into = c("Organ","Age.PCW"), sep = "_", remove = FALSE) %>%
  mutate(Age.PCW = parse_number(Age.PCW)) %>%
  arrange(Organ, Age.PCW)

avg.rna <- avg.rna[, col_info_rna$col, drop = FALSE]

ann_rna <- col_info_rna %>% dplyr::select(Organ, Age.PCW) %>% as.data.frame()
rownames(ann_rna) <- col_info_rna$col


p2 <- pheatmap(
  avg.rna,
  cluster_rows = FALSE, cluster_cols = FALSE, scale = "row",
  color = colorRampPalette(c("grey40","white","red"))(100),
  annotation_col = ann_rna,
  annotation_colors = list(Organ = region_cols, `Age.PCW` = age_cols),
  fontsize_row = 12, fontsize_col = 12,labels_col =  gsub(".*PCW","",colnames(avg.rna)),
  main = "RNA_Tip_cells"
)

# Export side-by-side
pdf("../Results/Manuscript/Figure2/Tip_cells/Tip_cells.degs.RNA.ATAC_age.pdf",width = 12,height = 6)
grid.arrange(grobs = list(p1[[4]], p2[[4]]), ncol = 2)
dev.off()

#_____________________________________________________Subtype+Organ_____________________________________________________

avg.atac <- AverageExpression(ATAC.all$`Tip cells`,group.by = c("Organ_subtypes"),features = common.set[-length(common.set)],assay = "ACTIVITY")$ACTIVITY
avg.rna <- AverageExpression(RNA.int$`Tip cells`,group.by = c("Organ_subtypes"),features = common.set[-length(common.set)],assay = "RNA")$RNA

colnames(avg.atac) <- c("Brain_tip-1", "Heart_tip-1")
colnames(avg.rna) <- c("Brain_tip-1", "Heart_tip-1")

col_info_atac <- tibble(col = colnames(avg.atac)) %>%
  separate(col, into = c("Region"), sep = "_", remove = FALSE) %>%
  arrange(Region)
avg.atac <- avg.atac[, col_info_atac$col, drop = FALSE]

ann_atac <- col_info_atac %>%
  dplyr::select(Region) %>%
  as.data.frame()
rownames(ann_atac) <- col_info_atac$col

region_cols <- c(Brain = "#3A86FF", Heart = "#2FBF71")

library(ggplotify)   # as.ggplot()

p1 <- as.ggplot(pheatmap(
  avg.atac,
  cluster_rows = FALSE, cluster_cols = FALSE, scale = "row",
  color = colorRampPalette(c("grey40","white","purple3"))(100),
  annotation_col = ann_atac,
  annotation_colors = list(Region = region_cols),
  fontsize_row = 12, fontsize_col = 12,
  main = "ATAC_Tip_cells",labels_col =  gsub(".*_","",colnames(avg.atac)),
))


col_info_rna <- tibble(col = colnames(avg.rna)) %>%
  separate(col, into = c("Organ"), sep = "_", remove = FALSE)
  

ann_rna <- col_info_rna %>% dplyr::select(Organ) %>% as.data.frame()
rownames(ann_rna) <- col_info_rna$col

p2 <- as.ggplot(pheatmap(
  avg.rna,
  cluster_rows = FALSE, cluster_cols = FALSE, scale = "row",
  color = colorRampPalette(c("grey40","white","red"))(100),
  annotation_col = ann_rna,
  annotation_colors = list(Organ = region_cols),
  fontsize_row = 12, fontsize_col = 12,
  main = "RNA_Tip_cells",labels_col =  gsub(".*_","",colnames(avg.rna)),
))


# Export side-by-side
pdf("../Results/Manuscript/Figure2/Tip_cells/Tip_cells.degs.RNA.ATAC.sub.pdf", width = 8, height = 6)
wrap_plots(p1, p2, ncol = 2)
dev.off()



```


```{r Tip_cells,fig.width=8,fig.height=5}


###############################################################################################################
################################################ Pathway analysis ##############################################
###############################################################################################################


load("./Cross_organ.celltype.degs_Tip_cells.Rdata")

open_Brain <- rownames(da_peaks.Tip_cells[da_peaks.Tip_cells$avg_log2FC > 3, ])
open_Heart <- rownames(da_peaks.Tip_cells[da_peaks.Tip_cells$avg_log2FC < -0.5, ])

DefaultAssay(ATAC.all$`Tip cells`) <- "Peak.celltype"
closest_genes_Brain <- ClosestFeature(ATAC.all$`Tip cells`, regions = open_Brain)
closest_genes_Heart <- ClosestFeature(ATAC.all$`Tip cells`, regions = open_Heart)

library(clusterProfiler)
library(org.Hs.eg.db)
library(enrichplot)

Brain_ego <- enrichGO(gene = closest_genes_Brain$gene_id,
                keyType = "ENSEMBL",
                OrgDb = org.Hs.eg.db,
                ont = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff = 0.05,
                qvalueCutoff = 0.05,
                readable = TRUE)

Heart_ego <- enrichGO(gene = closest_genes_Heart$gene_id,
                keyType = "ENSEMBL",
                OrgDb = org.Hs.eg.db,
                ont = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff = 0.05,
                qvalueCutoff = 0.05,
                readable = TRUE)


Brain.rna_ego <- enrichGO(gene = rownames(subset(RNA.Tip_cells.deg,avg_log2FC>3 & p_val_adj<0.01)),
                keyType = "SYMBOL",
                OrgDb = org.Hs.eg.db,
                ont = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff = 0.05,
                qvalueCutoff = 0.05,
                readable = TRUE)

Heart.rna_ego <- enrichGO(gene = rownames(subset(RNA.Tip_cells.deg,avg_log2FC< -3 & p_val_adj<0.01)),
                keyType = "SYMBOL",
                OrgDb = org.Hs.eg.db,
                ont = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff = 0.05,
                qvalueCutoff = 0.05,
                readable = TRUE)

p1 <- barplot(Brain_ego,showCategory = 15)+ggtitle("ATAC-Brain")
p2 <- barplot(Heart_ego,showCategory = 15)+ggtitle("ATAC-Heart")
p3 <- barplot(Brain.rna_ego,showCategory = 15)+ggtitle("RNA-Brain")
p4 <- barplot(Heart.rna_ego,showCategory = 15)+ggtitle("RNA-Heart")

pdf("../Results/Manuscript/Figure2/Tip_cells/Tip_cells.GO.pdf",width = 12,height = 14)
(p1+p3)/(p2+p4)
dev.off()

#_____________________________


library(clusterProfiler)
library(org.Hs.eg.db)
library(enrichplot)
library(dplyr)

# 1) Prepare lists (convert ATAC Ensembl → SYMBOL to use one keyType)
brain_atac_sym <- mapIds(org.Hs.eg.db,
                         keys = closest_genes_Brain$gene_id,
                         keytype = "ENSEMBL",
                         column = "SYMBOL",
                         multiVals = "first") %>% na.omit() %>% unique()

heart_atac_sym <- mapIds(org.Hs.eg.db,
                         keys = closest_genes_Heart$gene_id,   # <-- you probably have this
                         keytype = "ENSEMBL",
                         column = "SYMBOL",
                         multiVals = "first") %>% na.omit() %>% unique()

brain_rna <- rownames(subset(RNA.Tip_cells.deg,  avg_log2FC >  3 & p_val_adj < 0.01))
heart_rna <- rownames(subset(RNA.Tip_cells.deg,  avg_log2FC < -3 & p_val_adj < 0.01))

gene_sets <- list(
  Brain_ATAC = brain_atac_sym,
  Brain_RNA  = brain_rna,
  Heart_ATAC = heart_atac_sym,
  Heart_RNA  = heart_rna
)



# 2) One call → four enrichments, one combined result
ck <- compareCluster(geneCluster = gene_sets,
                     fun        = "enrichGO",
                     OrgDb      = org.Hs.eg.db,
                     keyType    = "SYMBOL",
                     ont        = "BP",
                     pAdjustMethod = "BH",
                     pvalueCutoff  = 0.05,
                     qvalueCutoff  = 0.05,
                     readable      = TRUE)



# 3) One figure (dotplot) — faceted by cluster (Brain/Heart × RNA/ATAC)

pdf("../Results/Manuscript/Figure2/Tip_cells/Tip_cells.GO.all.pdf",width = 6,height = 50)

dotplot(ck, showCategory = 50) +
  ggplot2::ggtitle("GO (BP): Brain/Heart × RNA/ATAC")+guides(size = "none") +rotate_x_text(90)+  ggplot2::scale_x_discrete(labels = function(x) gsub("\\s*\\(.*\\)$", "", x))
dev.off()

write.csv(ck@compareClusterResult,"../Results/Manuscript/Figure2/Tip_cells/Tip_cells.GO.all.csv")
x <- read.csv("../Results/Manuscript/Figure2/Tip_cells/Tip_cells.GO.all.csv")


# Selecting the biologicaly meaningful terms

terms <- c( "transport across blood-brain barrier","neuron migration","Wnt signaling pathway","regulation of neuron projection development","axonogenesis","forebrain development","telencephalon development", "mesenchyme development","heart morphogenesis","muscle tissue development","cardiac muscle hypertrophy","cardiac muscle cell development","cardiac chamber morphogenesis","cardiac muscle tissue growth","cardiac muscle cell differentiation","vascular process in circulatory system","vascular transport","connective tissue development","heart valve morphogenesis","cardiac chamber development","muscle cell differentiation","cardiac ventricle morphogenesis","ventricular cardiac muscle tissue development")



# Pull the results table, filter to your list, and lock the order
df <- as.data.frame(ck@compareClusterResult)
present <- intersect(terms, unique(df$Description))
missing  <- setdiff(terms, present)
if (length(missing)) message("Not found (will be dropped): ", paste(missing, collapse = "; "))

df_sub <- df %>%
  filter(Description %in% present) %>%
  mutate(Description = factor(Description, levels = terms))  # keep original order

# Put filtered table back into a compareClusterResult for dotplot()
ck_sub <- ck
ck_sub@compareClusterResult <- df_sub

pdf("../Results/Manuscript/Figure2/Tip_cells/Tip_cells.GO.selected.pdf",
    width = 5, height = 9)

dotplot(ck_sub, showCategory = Inf) +
  ggtitle("GO (BP)- Tip_cells") +
  guides(size = "none") +
  scale_x_discrete(drop = FALSE, labels = function(x) gsub("\\s*\\(.*\\)$", "", x)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

dev.off()

##################################DEGs in ATAC assay################################################
selected.term <- "transport across blood-brain barrier"
# regulation of neuron projection development
Brain_ATAC <- c(ck_sub@compareClusterResult[ck_sub@compareClusterResult$Description==selected.term,]$geneID)[1]
Brain_RNA <- c(ck_sub@compareClusterResult[ck_sub@compareClusterResult$Description==selected.term,]$geneID)[2]
Brain_ATAC <- unique(trimws(unlist(strsplit(Brain_ATAC, "/"))))
Brain_RNA <- unique(trimws(unlist(strsplit(Brain_RNA, "/"))))
Brain <- intersect(Brain_ATAC,Brain_RNA)

x <- subset(da_peaks.Tip_cells, p_val_adj<0.01)



DefaultAssay(ATAC.all$`Tip cells`) <- "Peak.celltype"
closest_genes <- ClosestFeature(ATAC.all$`Tip cells`, regions = rownames(x))
closest_genes <- subset(closest_genes, gene_name %in%Brain)


ATAC.all$`Tip cells`$Organ_Subtype.time <- paste0(ATAC.all$`Tip cells`$Organ,"_",ATAC.all$`Tip cells`$newL3_Subtype.multi.pred_2,"_",ATAC.all$`Tip cells`$Age.PCW)
Idents(ATAC.all$`Tip cells`) <- "Organ_Subtype.time"

ATAC.all$`Tip cells` <- SortIdents(ATAC.all$`Tip cells`)


DefaultAssay(ATAC.all$`Tip cells`) <- "Peak.celltype"


library(patchwork)
library(scales)

fmt_mb <- function(x) paste0(round(x/1e6, 2), " Mb")

pics <- list()
for (n in 1:length(closest_genes$gene_name)) {
  # pick a peak you care about (e.g., the one linked to your chosen gene)
p <- StringToGRanges(closest_genes$query_region[n])

# pad generously so the peak isn’t at the edge
p_ext <- Extend(p, upstream = 30000, downstream = 30000)

# p: a single-peak GRanges; p_ext: padded window
pics[[n]] <- CoveragePlot(
  object = ATAC.all$`Tip cells`,
  region = p_ext,
  region.highlight = p,
  group.by = "Organ_subtypes",
  tile.size = 100,
  downsample = TRUE,
  annotation = FALSE,  # <- important: no gene track here
  peaks = FALSE,       # <- and no peaks here
  links = FALSE
) &
  scale_x_continuous(labels = fmt_mb, n.breaks = 4) &   # only coverage gets Mb
  theme(
    axis.text.x  = element_text(size = 7, angle = 25, hjust = 1),
    axis.title.x = element_text(size = 8)
  )

peaks_panel <- PeakPlot(
  object = ATAC.all$`Tip cells`,
  region = p_ext
) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x  = element_blank(),
    axis.ticks.x = element_blank()
  )

genes_panel <- AnnotationPlot(
  object = ATAC.all$`Tip cells`,
  region = p_ext
) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x  = element_blank(),
    axis.ticks.x = element_blank()
  )

# stack them: coverage (styled axis), then peaks, then genes
pics[[n]] <- pics[[n]] / peaks_panel / genes_panel + plot_layout(heights = c(5, 1, 1))
}



library(ggpubr)

sel <- c(1,2)   # vascular transport

combined <- ggarrange(plotlist = pics[sel], ncol = 2, nrow = 1)

pdf(paste0("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Projects/Tiantan/Results/Manuscript/Figure2/Tip_cells/Tip_cells.Coverage.",selected.term,".pdf"),
    width = 6, height = 4) 
annotate_figure(
  combined,
  top = text_grob(selected.term, face = "bold", size = 16, vjust = 1)
)
dev.off()



#"cell growth involved in cardiac muscle cell development"

selected.term <- "cardiac ventricle morphogenesis"

# regulation of neuron projection development
Heart_ATAC <- c(ck_sub@compareClusterResult[ck_sub@compareClusterResult$Description==selected.term,]$geneID)[1]
Heart_RNA <- c(ck_sub@compareClusterResult[ck_sub@compareClusterResult$Description==selected.term,]$geneID)[2]
Heart_ATAC <- unique(trimws(unlist(strsplit(Heart_ATAC, "/"))))
Heart_RNA <- unique(trimws(unlist(strsplit(Heart_RNA, "/"))))
Heart <- intersect(Heart_ATAC,Heart_RNA)


x <- subset(da_peaks.Tip_cells, p_val_adj<0.01)

DefaultAssay(ATAC.all$`Tip cells`) <- "Peak.celltype"
closest_genes <- ClosestFeature(ATAC.all$`Tip cells`, regions = rownames(x))
closest_genes <- subset(closest_genes, gene_name %in%Heart)


ATAC.all$`Tip cells`$Organ_Subtype.time <- paste0(ATAC.all$`Tip cells`$Organ,"_",ATAC.all$`Tip cells`$newL3_Subtype.multi.pred_2,"_",ATAC.all$`Tip cells`$Age.PCW)
Idents(ATAC.all$`Tip cells`) <- "Organ_Subtype.time"

ATAC.all$`Tip cells` <- SortIdents(ATAC.all$`Tip cells`)


DefaultAssay(ATAC.all$`Tip cells`) <- "Peak.celltype"


fmt_mb <- function(x) paste0(round(x/1e6, 2), " Mb")

pics <- list()
for (n in 1:length(closest_genes$gene_name)) {
  # pick a peak you care about (e.g., the one linked to your chosen gene)
p <- StringToGRanges(closest_genes$query_region[n])

# pad generously so the peak isn’t at the edge
p_ext <- Extend(p, upstream = 10000, downstream = 10000)

# p: a single-peak GRanges; p_ext: padded window
pics[[n]] <- CoveragePlot(
  object = ATAC.all$`Tip cells`,
  region = p_ext,
  region.highlight = p,
  group.by = "Organ_subtypes",
  tile.size = 100,
  downsample = TRUE,
  annotation = FALSE,  # <- important: no gene track here
  peaks = FALSE,       # <- and no peaks here
  links = FALSE
) &
  scale_x_continuous(labels = fmt_mb, n.breaks = 4) &   # only coverage gets Mb
  theme(
    axis.text.x  = element_text(size = 7, angle = 25, hjust = 1),
    axis.title.x = element_text(size = 8)
  )

peaks_panel <- PeakPlot(
  object = ATAC.all$`Tip cells`,
  region = p_ext
) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x  = element_blank(),
    axis.ticks.x = element_blank()
  )

genes_panel <- AnnotationPlot(
  object = ATAC.all$`Tip cells`,
  region = p_ext
) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x  = element_blank(),
    axis.ticks.x = element_blank()
  )

# stack them: coverage (styled axis), then peaks, then genes
pics[[n]] <- pics[[n]] / peaks_panel / genes_panel + plot_layout(heights = c(5, 1, 1))
}



library(ggpubr)

sel <- c(1)   # regulation of neuron projection development

combined <- ggarrange(plotlist = pics[sel], ncol = 1, nrow = 1)

pdf(paste0("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Projects/Tiantan/Results/Manuscript/Figure2/Tip_cells/Tip_cells.Coverage.",selected.term,".pdf"),
    width = 3, height = 4) 
annotate_figure(
  combined,
  top = text_grob("cardiac ventricle\n morphogenesis", face = "bold", size = 16, vjust = 1)
)
dev.off()


```


```{r Tip_cells,fig.width=8,fig.height=5}


##### Chromvar

Idents(ATAC.all$`Tip cells`) <- "Organ"
DefaultAssay(ATAC.all$`Tip cells`) <- 'chromvar'

differential.activity <- FindMarkers(
  object = ATAC.all$`Tip cells`,
  ident.1 = 'Brain',
  ident.2 = 'Heart',
  only.pos = FALSE,
  mean.fxn = rowMeans,  
  logfc.threshold = 0,
  fc.name = "avg_diff"
)

differential.activity$Motifs <- names(unlist(ATAC.all$`Tip cells`@assays$Peak.celltype@motifs@motif.names)[rownames(differential.activity)])  
differential.activity$Motifs.names <- (unlist(ATAC.all$`Tip cells`@assays$Peak.celltype@motifs@motif.names)[rownames(differential.activity)])  




# Start from your table:
da <- differential.activity

# Ensure we have a readable label (fall back to motif ID if name missing)
da$label_base <- ifelse(is.na(da$Motifs.names) | da$Motifs.names == "",
                        da$Motifs, da$Motifs.names)

# Protect against p_val_adj == 0 (so -log10 is finite)
da$padj_safe <- ifelse(da$p_val_adj == 0, .Machine$double.xmin, da$p_val_adj)
da$mlog10    <- -log10(da$padj_safe)

# Direction for coloring
da$direction <- ifelse(da$avg_diff > 0, "Brain↑",
                       ifelse(da$avg_diff < 0, "Heart↑", "0"))

# Pick top-10 each side by effect size (use only significant if you want)
sig_cut <- 0.05
da_sig  <- da %>% filter(p_val_adj < sig_cut)

top_up   <- da_sig %>% filter(avg_diff > 0) %>%
  arrange(desc(avg_diff)) %>% slice_head(n = 5)

top_down <- da_sig %>% filter(avg_diff < 0) %>%
  arrange(avg_diff) %>% slice_head(n = 5)

to_label_ids <- c(rownames(top_up), rownames(top_down))

da$label <- ifelse(rownames(da) %in% to_label_ids, da$label_base, "")

# Volcano
vline_x  <- 0
hline_y  <- -log10(sig_cut)

da$direction <- factor(da$direction,levels = c("Heart↑","Brain↑"))
p <- ggplot(da, aes(x = avg_diff, y = mlog10)) +
  geom_point(aes(color = direction), alpha = 0.6, size = 1.4) +
  geom_vline(xintercept = vline_x, linetype = 2) +
  geom_hline(yintercept = hline_y, linetype = 2) +
  scale_color_manual(
    values = c( "Heart↑" = "#2FBF71",  # cool for Heart-enriched
                "Brain↑" = "#3A86FF",  # warm for Brain-enriched
                "0"   = "grey70"),
    breaks = c( "Heart↑","Brain↑"),
    name = NULL
  ) +
  geom_text_repel(
    data = subset(da, label != ""),
    aes(label = label),
    size = 4,
    min.segment.length = 0,
    max.overlaps = Inf,max.time = 1,max.iter = 50000,
    box.padding = 0.5, point.padding = 0.2,segment.size = 0.3,segment.colour = "grey50",
  ) +
  labs(
    x = "Effect size (avg_diff)\n(+ Brain higher, – Heart higher)",
    y = expression(-log[10]("adj. p")),
    title = "Motif activity: Brain vs Heart (Tip_cells)"
  ) +
  theme_classic() +
  theme(legend.position = "top")



pdf("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Projects/Tiantan/Results/Manuscript/Figure2/Tip_cells/Tip_cells.vln.motifs.pdf",height = 3.5,width = 4.5)
p
dev.off()

x <- subset(differential.activity, p_val_adj<0.01)
x.up.Brain <- x[order(-x$avg_diff  , -x$p_val_adj),][1:12,]
x.down.Heart <- x[order(x$avg_diff, -x$p_val_adj),][1:12,]


mot.brain <- MotifPlot(
  object = ATAC.all$`Tip cells`,
  motifs = rownames(x.up.Brain),
  assay = "Peak.celltype"
)+labs(subtitle = "Brain-Tip_cells")

mot.heart <- MotifPlot(
  object = ATAC.all$`Tip cells`,
  motifs = rownames(x.down.Heart),
  assay = "Peak.celltype"
)+labs(subtitle = "Heart-Tip_cells")



pdf("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Projects/Tiantan/Results/Manuscript/Figure2/Tip_cells/Tip_cells.motifs.pdf",width = 20, height = 5) 
mot.brain+mot.heart
dev.off()



ATAC.all$`Tip cells`$Organ_subtypes <- paste0(ATAC.all$`Tip cells`$Organ,"_",ATAC.all$`Tip cells`$newL3_Subtype.multi.pred_2)

differential.activity <- FindAllMarkers(
  object = ATAC.all$`Tip cells`,
  group.by = "Organ_subtypes",
  only.pos = FALSE,
  logfc.threshold = 0
)

differential.activity$Motifs <- names(unlist(ATAC.all$`Tip cells`@assays$Peak.celltype@motifs@motif.names)[differential.activity$gene])  
differential.activity$Motifs.names <- (unlist(ATAC.all$`Tip cells`@assays$Peak.celltype@motifs@motif.names)[differential.activity$gene])  


top5.motifs <- c()
for (clusters in unique(differential.activity$cluster)) {
  x <- subset(differential.activity, cluster == clusters )
  x <- x[order(-x$avg_log2FC, -x$p_val_adj),][1:10,]
  top5.motifs <- rbind(top5.motifs,x)
}


top.motif.avg <- as.data.frame(AverageExpression(ATAC.all$`Tip cells`,assays = "chromvar",unique(top5.motifs$Motifs),group.by = c("Organ_subtypes"))$chromvar)
# top5.motifs <- top5.motifs[-25,]
top.motif.avg$mot.name <- top5.motifs[top5.motifs$Motifs%in%rownames(top.motif.avg),]$Motifs.names
rownames(top.motif.avg) <- paste0(unique(top.motif.avg$mot.name),"(",rownames(top.motif.avg),")")
top.motif.avg <- top.motif.avg[,-dim(top.motif.avg)[2]]

col_info_atac <- tibble(col = colnames(top.motif.avg)) %>%
  separate(col, into = c("Region"), sep = "-", remove = FALSE) %>%
  arrange(Region)
top.motif.avg <- top.motif.avg[, col_info_atac$col, drop = FALSE]

ann_atac <- col_info_atac %>%
  dplyr::select(Region) %>%
  as.data.frame()
rownames(ann_atac) <- col_info_atac$col

region_cols <- c(Brain = "#3A86FF", Heart = "#2FBF71")

library(ggplotify)   # as.ggplot()
p1 <- as.ggplot(pheatmap(
  top.motif.avg,
  cluster_rows = TRUE, cluster_cols = TRUE, scale = "row",
  color = colorRampPalette(c("grey40","white","purple3"))(100),
  annotation_col = ann_atac,
  annotation_colors = list(Region = region_cols),
  fontsize_row = 12, fontsize_col = 12,
  main = "ATAC_Tip_cells",labels_col =  sub("^[^-]*-", "", colnames(top.motif.avg))
))+labs(subtitle = "Motif activity")

pdf("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Projects/Tiantan/Results/Manuscript/Figure2/Tip_cells/Tip_cells.motifs.subtype.pdf",width = 6, height = 8) 
 p1
dev.off()

```





