---
title: "ECs_Capillary"
output: html_document
date: "2026-03-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE,message=FALSE}

knitr::opts_chunk$set(echo                  = FALSE
                      ,warning              = FALSE
                      ,message              = FALSE
                      ,error                = TRUE
                      ,dev                  = c('png','pdf')
                      ,pdf.options(encoding = "ISOLatin9.enc", useKerning=FALSE, useDingbats=FALSE))

```


A report by **Elyas.Mohammadi**


```{r libraries}

# Changing the Seurat version to 5
.libPaths("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Rloading/4.4.Spatial/")
library(tibble)
library(ggplot2)

# install.packages('Seurat')
unloadNamespace("Seurat")  
library(Seurat)

.libPaths("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Rloading/4.4/")

# library(data.table)
library(harmony)


library(ggrepel)
library(ggpubr)
library(patchwork)
# library(clusterProfiler)
# library(org.Hs.eg.db)
library(AnnotationHub)
# library(EnsDb.Hsapiens.v86)
library(ggthemes)
library(viridis)
library(dplyr)
library(GenomicRanges)
library(GenomeInfoDb)
library(tidyr)
library(RColorBrewer)
library(scales)
library(gridExtra)
library(pheatmap)

library(ggh4x)
axis <- ggh4x::guide_axis_truncated(
  trunc_lower = unit(0, "npc"),
  trunc_upper = unit(1.5, "cm"))

library(Signac)

```


# ECs_Cpillary

```{r ECs_Cpillary,fig.width=15,fig.height=20}
ATAC.all <- readRDS("./ATAC.all.int3_2.splitted.Rds")
RNA.int <- readRDS("./RNA.int_2.splitted.Rds")
meta <- readRDS("./meta.Rds")


# Trying to find DEGs celltypes in RNA and ATAC (ACTIVITY assay) data
###############################################################################################################
################################################ DEGs #######################################################
###############################################################################################################

DefaultAssay(ATAC.all$ECs_Cpillary) <- "ACTIVITY"
# 
# ATAC.ECs_Cpillary.deg <- FindMarkers(ATAC.all$ECs_Cpillary,ident.1 = "Brain",ident.2 = "Heart",logfc.threshold = 0.5,test.use = "MAST",latent.vars = "Source2",group.by = "Region",assay = "ACTIVITY")
# RNA.ECs_Cpillary.deg <- FindMarkers(RNA.int$ECs_Cpillary,ident.1 = "Brain",ident.2 = "Heart",logfc.threshold = 0.5,test.use = "MAST",latent.vars = "Dataset",group.by = "Organ")
# save(ATAC.ECs_Cpillary.deg,RNA.ECs_Cpillary.deg,file = "./Cross_organ.celltype.degs_ECs_Cpillary.Rdata")
# 
# 
# DefaultAssay(ATAC.all$ECs_Cpillary) <- 'Peak.celltype'
# 
# # wilcox is the default option for test.use
# da_peaks.ECs_Cpillary <- FindMarkers(
#   object = ATAC.all$ECs_Cpillary,
#   ident.1 = "Brain",
#   ident.2 = "Heart",
#   test.use = 'LR',
#   min.pct = 0.05,
#   latent.vars = c('nCount_peaks',"Source"),group.by = "Region"
# )
# saveRDS(da_peaks.ECs_Cpillary,"./Cross_organ.celltype.degs_ECs_Cpillary.Rds")
# save(ATAC.ECs_Cpillary.deg,RNA.ECs_Cpillary.deg,da_peaks.ECs_Cpillary,file = "./Cross_organ.celltype.degs_ECs_Cpillary.Rdata")

load(file = "./Cross_organ.celltype.degs_ECs_Cpillary.Rdata")


# load(file = "./Cross_organ.celltype.degs_ECs_Cpillary.Rdata")


x <- subset(ATAC.ECs_Cpillary.deg, p_val_adj<0.01)
x.up <- x[order(-x$avg_log2FC, -x$p_val_adj),][1:100,]
x.down <- x[order(x$avg_log2FC, -x$p_val_adj),][1:100,]
x.up$Direction <- "Up"
x.down$Direction <- "Down"
tops.atac.ECs_Cpillary <- rbind(x.up,x.down)
tops.atac.ECs_Cpillary$gene <- rownames(tops.atac.ECs_Cpillary)

x <- subset(RNA.ECs_Cpillary.deg, p_val_adj<0.01)
x.up <- x[order(-x$avg_log2FC, -x$p_val_adj),][1:100,]
x.down <- x[order(x$avg_log2FC, -x$p_val_adj),][1:100,]
x.up$Direction <- "Up"
x.down$Direction <- "Down"
tops.rna.ECs_Cpillary <- rbind(x.up,x.down)
tops.rna.ECs_Cpillary$gene <- rownames(tops.rna.ECs_Cpillary)

common.set <- intersect(tops.atac.ECs_Cpillary$gene,tops.rna.ECs_Cpillary$gene)
avg.atac <- AverageExpression(ATAC.all$ECs_Cpillary,group.by = "Organ",features = common.set,assay = "ACTIVITY")$ACTIVITY
avg.rna <- AverageExpression(RNA.int$ECs_Cpillary,group.by = "Organ",features = common.set,assay = "RNA")$RNA

p1 <- pheatmap(
  avg.atac,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  scale = "row",           # optional: scales expression values per gene
  color = colorRampPalette(c("grey40", "white", "purple3"))(100),
  fontsize_row = 12,
  fontsize_col = 12,main = "ATAC_ECs_Cpillary"
)

p2 <- pheatmap(
  avg.rna,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  scale = "row",           # optional: scales expression values per gene
  color = colorRampPalette(c("grey40", "white", "red"))(100),
  fontsize_row = 12,
  fontsize_col = 12,main = "RNA_ECs_Cpillary"
)

pdf("../Results/Manuscript/Figure2/ECs_Cpillary/ECs_Cpillary.degs.RNA.ATAC.pdf",width = 6.5,height = 6)
grid.arrange(grobs = list(p1[[4]],p2[[4]]), ncol = 2)
dev.off()

#_____________________________________________________Age+Organ_____________________________________________________

avg.atac <- AverageExpression(ATAC.all$ECs_Cpillary,group.by = c("Organ","Age.PCW"),features = common.set,assay = "ACTIVITY")$ACTIVITY
avg.rna <- AverageExpression(RNA.int$ECs_Cpillary,group.by = c("Organ","Age.PCW"),features = common.set,assay = "RNA")$RNA

library(dplyr)
library(tidyr)
library(stringr)
library(readr)   # for parse_number()

col_info_atac <- tibble(col = colnames(avg.atac)) %>%
  separate(col, into = c("Region","Age.PCW"), sep = "_", remove = FALSE) %>%
  mutate(Age.PCW = parse_number(Age.PCW)) %>%   # turns "PCW06" -> 6, "PCW10" -> 10
  arrange(Region, Age.PCW)
avg.atac <- avg.atac[, col_info_atac$col, drop = FALSE]

ann_atac <- col_info_atac %>%
  dplyr::select(Region, Age.PCW) %>%
  as.data.frame()
rownames(ann_atac) <- col_info_atac$col

region_cols <- c(Brain = "#3A86FF", Heart = "#2FBF71")
age_cols   <- colorRampPalette(c("#F5F9FF", "lightblue","blue", "darkblue"))(10)


labels_atac <- as.character(col_info_atac$Age.PCW)

p1 <- pheatmap(
  avg.atac,
  cluster_rows = FALSE, cluster_cols = FALSE, scale = "row",
  color = colorRampPalette(c("grey40","white","purple3"))(100),
  annotation_col = ann_atac,
  annotation_colors = list(Region = region_cols, `Age.PCW` = age_cols),
  fontsize_row = 12, fontsize_col = 12,labels_col = gsub(".*PCW","",colnames(avg.atac)),
  main = "ATAC_ECs_Cpillary"
)

col_info_rna <- tibble(col = colnames(avg.rna)) %>%
  separate(col, into = c("Organ","Age.PCW"), sep = "_", remove = FALSE) %>%
  mutate(Age.PCW = parse_number(Age.PCW)) %>%
  arrange(Organ, Age.PCW)

avg.rna <- avg.rna[, col_info_rna$col, drop = FALSE]

ann_rna <- col_info_rna %>% dplyr::select(Organ, Age.PCW) %>% as.data.frame()
rownames(ann_rna) <- col_info_rna$col


p2 <- pheatmap(
  avg.rna,
  cluster_rows = FALSE, cluster_cols = FALSE, scale = "row",
  color = colorRampPalette(c("grey40","white","red"))(100),
  annotation_col = ann_rna,
  annotation_colors = list(Organ = region_cols, `Age.PCW` = age_cols),
  fontsize_row = 12, fontsize_col = 12,labels_col =  gsub(".*PCW","",colnames(avg.rna)),
  main = "RNA_ECs_Cpillary"
)

# Export side-by-side
pdf("../Results/Manuscript/Figure2/ECs_Cpillary/ECs_Cpillary.degs.RNA.ATAC_age.pdf",width = 12,height = 6)
grid.arrange(grobs = list(p1[[4]], p2[[4]]), ncol = 2)
dev.off()

#_____________________________________________________Subtype+Organ_____________________________________________________

avg.atac <- AverageExpression(ATAC.all$ECs_Cpillary,group.by = c("Organ","newL3_Subtype.multi.pred_2"),features = common.set,assay = "ACTIVITY")$ACTIVITY
avg.rna <- AverageExpression(RNA.int$ECs_Cpillary,group.by = c("Organ","newL3_Subtype"),features = common.set,assay = "RNA")$RNA


col_info_atac <- tibble(col = colnames(avg.atac)) %>%
  separate(col, into = c("Region"), sep = "_", remove = FALSE) %>%
  arrange(Region)
avg.atac <- avg.atac[, col_info_atac$col, drop = FALSE]

ann_atac <- col_info_atac %>%
  dplyr::select(Region) %>%
  as.data.frame()
rownames(ann_atac) <- col_info_atac$col

region_cols <- c(Brain = "#3A86FF", Heart = "#2FBF71")

library(ggplotify)   # as.ggplot()

p1 <- as.ggplot(pheatmap(
  avg.atac,
  cluster_rows = FALSE, cluster_cols = FALSE, scale = "row",
  color = colorRampPalette(c("grey40","white","purple3"))(100),
  annotation_col = ann_atac,
  annotation_colors = list(Region = region_cols),
  fontsize_row = 12, fontsize_col = 12,
  main = "ATAC_ECs_Cpillary",labels_col =  gsub(".*_","",colnames(avg.atac)),
))


col_info_rna <- tibble(col = colnames(avg.rna)) %>%
  separate(col, into = c("Organ"), sep = "_", remove = FALSE)
  

ann_rna <- col_info_rna %>% dplyr::select(Organ) %>% as.data.frame()
rownames(ann_rna) <- col_info_rna$col

p2 <- as.ggplot(pheatmap(
  avg.rna,
  cluster_rows = FALSE, cluster_cols = FALSE, scale = "row",
  color = colorRampPalette(c("grey40","white","red"))(100),
  annotation_col = ann_rna,
  annotation_colors = list(Organ = region_cols),
  fontsize_row = 12, fontsize_col = 12,
  main = "RNA_ECs_Cpillary",labels_col =  gsub(".*_","",colnames(avg.rna)),
))


# Export side-by-side
pdf("../Results/Manuscript/Figure2/ECs_Cpillary/ECs_Cpillary.degs.RNA.ATAC.sub.pdf", width = 8, height = 6)
wrap_plots(p1, p2, ncol = 2)
dev.off()



```


```{r ECs_Cpillary,fig.width=8,fig.height=5}


###############################################################################################################
################################################ Pathway analysis ##############################################
###############################################################################################################


load("./Cross_organ.celltype.degs_ECs_Cpillary.Rdata")

open_Brain <- rownames(da_peaks.ECs_Cpillary[da_peaks.ECs_Cpillary$avg_log2FC > 3, ])
open_Heart <- rownames(da_peaks.ECs_Cpillary[da_peaks.ECs_Cpillary$avg_log2FC < -0.5, ])

DefaultAssay(ATAC.all$ECs_Cpillary) <- "Peak.celltype"
closest_genes_Brain <- ClosestFeature(ATAC.all$ECs_Cpillary, regions = open_Brain)
closest_genes_Heart <- ClosestFeature(ATAC.all$ECs_Cpillary, regions = open_Heart)

library(clusterProfiler)
library(org.Hs.eg.db)
library(enrichplot)

Brain_ego <- enrichGO(gene = closest_genes_Brain$gene_id,
                keyType = "ENSEMBL",
                OrgDb = org.Hs.eg.db,
                ont = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff = 0.05,
                qvalueCutoff = 0.05,
                readable = TRUE)

Heart_ego <- enrichGO(gene = closest_genes_Heart$gene_id,
                keyType = "ENSEMBL",
                OrgDb = org.Hs.eg.db,
                ont = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff = 0.05,
                qvalueCutoff = 0.05,
                readable = TRUE)


Brain.rna_ego <- enrichGO(gene = rownames(subset(RNA.ECs_Cpillary.deg,avg_log2FC>3 & p_val_adj<0.01)),
                keyType = "SYMBOL",
                OrgDb = org.Hs.eg.db,
                ont = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff = 0.05,
                qvalueCutoff = 0.05,
                readable = TRUE)

Heart.rna_ego <- enrichGO(gene = rownames(subset(RNA.ECs_Cpillary.deg,avg_log2FC< -3 & p_val_adj<0.01)),
                keyType = "SYMBOL",
                OrgDb = org.Hs.eg.db,
                ont = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff = 0.05,
                qvalueCutoff = 0.05,
                readable = TRUE)

p1 <- barplot(Brain_ego,showCategory = 15)+ggtitle("ATAC-Brain")
p2 <- barplot(Heart_ego,showCategory = 15)+ggtitle("ATAC-Heart")
p3 <- barplot(Brain.rna_ego,showCategory = 15)+ggtitle("RNA-Brain")
p4 <- barplot(Heart.rna_ego,showCategory = 15)+ggtitle("RNA-Heart")

pdf("../Results/Manuscript/Figure2/ECs_Cpillary/ECs_Cpillary.GO.pdf",width = 12,height = 14)
(p1+p3)/(p2+p4)
dev.off()

#_____________________________


library(clusterProfiler)
library(org.Hs.eg.db)
library(enrichplot)
library(dplyr)

# 1) Prepare lists (convert ATAC Ensembl → SYMBOL to use one keyType)
brain_atac_sym <- mapIds(org.Hs.eg.db,
                         keys = closest_genes_Brain$gene_id,
                         keytype = "ENSEMBL",
                         column = "SYMBOL",
                         multiVals = "first") %>% na.omit() %>% unique()

heart_atac_sym <- mapIds(org.Hs.eg.db,
                         keys = closest_genes_Heart$gene_id,   # <-- you probably have this
                         keytype = "ENSEMBL",
                         column = "SYMBOL",
                         multiVals = "first") %>% na.omit() %>% unique()

brain_rna <- rownames(subset(RNA.ECs_Cpillary.deg,  avg_log2FC >  3 & p_val_adj < 0.01))
heart_rna <- rownames(subset(RNA.ECs_Cpillary.deg,  avg_log2FC < -3 & p_val_adj < 0.01))

gene_sets <- list(
  Brain_ATAC = brain_atac_sym,
  Brain_RNA  = brain_rna,
  Heart_ATAC = heart_atac_sym,
  Heart_RNA  = heart_rna
)



# 2) One call → four enrichments, one combined result
ck <- compareCluster(geneCluster = gene_sets,
                     fun        = "enrichGO",
                     OrgDb      = org.Hs.eg.db,
                     keyType    = "SYMBOL",
                     ont        = "BP",
                     pAdjustMethod = "BH",
                     pvalueCutoff  = 0.05,
                     qvalueCutoff  = 0.05,
                     readable      = TRUE)



# 3) One figure (dotplot) — faceted by cluster (Brain/Heart × RNA/ATAC)

pdf("../Results/Manuscript/Figure2/ECs_Cpillary/ECs_Cpillary.GO.all.pdf",width = 6,height = 50)

dotplot(ck, showCategory = 50) +
  ggplot2::ggtitle("GO (BP): Brain/Heart × RNA/ATAC")+guides(size = "none") +rotate_x_text(90)+  ggplot2::scale_x_discrete(labels = function(x) gsub("\\s*\\(.*\\)$", "", x))
dev.off()

write.csv(ck@compareClusterResult,"../Results/Manuscript/Figure2/ECs_Cpillary/ECs_Cpillary.GO.all.csv")
x <- read.csv("../Results/Manuscript/Figure2/ECs_Cpillary/ECs_Cpillary.GO.all.csv")


# Selecting the biologicaly meaningful terms

terms <- c("regulation of neuron projection development","axonogenesis","regulation of nervous system development","forebrain development","telencephalon development","regulation of synapse organization","transport across blood−brain barrier", "mesenchyme development","cardiac muscle tissue
development","muscle organ development","heart morphogenesis","muscle tissue development","cardiac muscle hypertrophy","Regulation of muscle system process","ventricular cardiac muscle","cell growth involved in cardiac muscle cell development","cardiac muscle cell development","cardiac chamber morphogenesis","cardiac muscle tissue growth","cardiac muscle cell differentiation")


# Pull the results table, filter to your list, and lock the order
df <- as.data.frame(ck@compareClusterResult)
present <- intersect(terms, unique(df$Description))
missing  <- setdiff(terms, present)
if (length(missing)) message("Not found (will be dropped): ", paste(missing, collapse = "; "))

df_sub <- df %>%
  filter(Description %in% present) %>%
  mutate(Description = factor(Description, levels = terms))  # keep original order

# Put filtered table back into a compareClusterResult for dotplot()
ck_sub <- ck
ck_sub@compareClusterResult <- df_sub

pdf("../Results/Manuscript/Figure2/ECs_Cpillary/ECs_Cpillary.GO.selected.pdf",
    width = 5, height = 8)

dotplot(ck_sub, showCategory = Inf) +
  ggtitle("GO (BP)- ECs_Cpillary") +
  guides(size = "none") +
  scale_x_discrete(drop = FALSE, labels = function(x) gsub("\\s*\\(.*\\)$", "", x)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

dev.off()


### Selecting some terms that chromatin is open but RNA is not expressed in one organ

x <- as.character(ck_sub@compareClusterResult$geneID[39])   # 4: "forebrain development", 33 = "cardiac muscle cell differentiation"
genes <- unique(trimws(strsplit(x, "/", fixed = TRUE)[[1]]))
genes

library(dplyr)
library(tidyr)
library(ggplot2)
library(gghalves)

# ---- inputs ----
genes <- c("SLC2A1") # Brain enriched genes fr forebrain development
genes <- c("GATA6") # Heart enriched genes fr cardiac muscle cell differentiation

obj   <- RNA.int$ECs_Cpillary
DefaultAssay(obj) <- "RNA"

# tidy expression for the selected genes
df <- Seurat::FetchData(obj, vars = c("Organ", genes), slot = "data") %>%
    tibble::rownames_to_column("cell") %>%
    pivot_longer(cols = all_of(genes), names_to = "gene", values_to = "expr") %>%
    mutate(
        Organ = factor(Organ, levels = c("Brain","Heart")),
        gene  = factor(gene,  levels = genes)
    )

cols <- c(Brain = "#3A86FF", Heart = "#2FBF71")

p2 <- ggplot(df, aes(x = gene, y = expr)) +
    # left half = Heart
    gghalves::geom_half_violin(
        data  = ~ subset(.x, Organ == "Heart"),
        aes(fill = "Heart"),
        side  = "l", width = 0.9, trim = TRUE, alpha = 0.95
    ) +
    # right half = Brain
    gghalves::geom_half_violin(
        data  = ~ subset(.x, Organ == "Brain"),
        aes(fill = "Brain"),
        side  = "r", width = 0.9, trim = TRUE, alpha = 0.95
    ) +
    scale_fill_manual(values = cols, breaks = c("Brain","Heart"), name = "Organ") +
    labs(x = NULL, y = "Expression (RNA level)") +
    theme_classic() +
    theme(
        legend.position = "top",
        axis.text.x = element_text(angle = 25, hjust = 1)
    )+ggtitle("Cardiac chamber morphogenesis")  # "Forebrain development"and "cardiac chamber morphogenesis"


final <- (p1 + p2) +
    plot_layout(widths = c(1, 1), guides = "collect") +
    plot_annotation(theme = theme(legend.position = "right")) &
    theme(plot.margin = margin(5, 5, 5, 5))  # same margins for both

pdf("../Results/Manuscript/Final_refinments/ED5/ED5.RNAsupportForPathway.pdf",width = 7,height = 3)

final
dev.off()


# consistent order + colors
ATAC.all$ECs_Cpillary$Organ <- factor(ATAC.all$ECs_Cpillary$Organ,
                                      levels = c("Brain","Heart"))
organ_cols <- c(Brain = "#3A86FF", Heart = "#2FBF71")

cov <- CoveragePlot(
  object    = ATAC.all$ECs_Cpillary,
  region    = c("SLC2A1","GATA6"),
  group.by  = "Organ",
  tile.size = 100,
  downsample= TRUE,
  annotation= TRUE,
  peaks     = FALSE,
  links     = TRUE
) &
  scale_fill_manual(values = organ_cols, name = "Organ") &
  theme(legend.position = "right")

pdf("../Results/Manuscript/Final_refinments/ED5/ED5.RNAsupportForPathway.ATAC.pdf",width = 10,height = 3)
cov
dev.off()

##################################DEGs in ATAC assay################################################

# regulation of neuron projection development
Brain_ATAC <- c(ck_sub@compareClusterResult[ck_sub@compareClusterResult$Description=="regulation of neuron projection development",]$geneID)[1]
Brain_RNA <- c(ck_sub@compareClusterResult[ck_sub@compareClusterResult$Description=="regulation of neuron projection development",]$geneID)[2]
Brain_ATAC <- unique(trimws(unlist(strsplit(Brain_ATAC, "/"))))
Brain_RNA <- unique(trimws(unlist(strsplit(Brain_RNA, "/"))))
Brain <- intersect(Brain_ATAC,Brain_RNA)


x <- subset(da_peaks.ECs_Cpillary, p_val_adj<0.01)

DefaultAssay(ATAC.all$ECs_Cpillary) <- "Peak.celltype"
closest_genes <- ClosestFeature(ATAC.all$ECs_Cpillary, regions = rownames(x))
closest_genes <- subset(closest_genes, gene_name %in%Brain)


ATAC.all$ECs_Cpillary$Organ_Subtype <- paste0(ATAC.all$ECs_Cpillary$Organ,"_",ATAC.all$ECs_Cpillary$newL3_Subtype.multi.pred_2)
Idents(ATAC.all$ECs_Cpillary) <- "Organ_Subtype"

ATAC.all$ECs_Cpillary <- SortIdents(ATAC.all$ECs_Cpillary)


DefaultAssay(ATAC.all$ECs_Cpillary) <- "Peak.celltype"

avg.atac.pathway <- AverageExpression(ATAC.all$ECs_Cpillary,features = unique(closest_genes$gene_name),group.by = c("Organ","newL3_Subtype.multi.pred_2") )$ACTIVITY
avg.rna.pathway <- AverageExpression(RNA.int$ECs_Cpillary,features = rownames(avg.atac.pathway) ,group.by = c("Organ","newL3_Subtype"))$RNA

## (Optional but recommended) Row-wise z-score within each modality
A.z <- t(scale(t(avg.atac.pathway)))   # ATAC activity, per gene across groups
R.z <- t(scale(t(avg.rna.pathway)))   # RNA expression, per gene across groups

# Per-gene correlations across groups
per_gene_cor <- vapply(
  seq_len(nrow(A.z)),
  function(i) cor(A.z[i, ], R.z[i, ], method = "pearson", use = "complete.obs"),
  numeric(1)
)
names(per_gene_cor) <- rownames(A.z)

# (Optional) focus on the most informative genes to keep the plot readable
# e.g., top 200 by absolute correlation:
keep <- order(abs(per_gene_cor), decreasing = TRUE)
per_gene_cor_top <- per_gene_cor[keep][seq_len(min(200, length(per_gene_cor)))]

# Make a 1-column matrix for heatmap
per_gene_mat <- matrix(per_gene_cor_top, ncol = 1,
                       dimnames = list(names(per_gene_cor_top), "corr(ATAC,RNA)"))
colnames(per_gene_mat) <- "Correlation"


library(RColorBrewer)
# 1) Cap values to [-1, 1] just in case
mat <- per_gene_mat
mat[mat >  1] <- 1
mat[mat < -1] <- -1

# 2) Make a diverging palette (blue → white → red), 100 steps
pal <- colorRampPalette(rev(brewer.pal(11, "RdBu")))(100)

# 3) Breaks must be length(colors)+1 to span exactly [-1, 1]
brks <- seq(-1, 1, length.out = length(pal) + 1)

pdf("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Projects/Tiantan/Results/Manuscript/Figure2/ECs_Cpillary/ECs_Cpillary.Coverage.atac.rna.cor.pdf",width = 2.5,height = 4)

pheatmap(
  mat,
  color         = pal,
  breaks        = brks,          # fixes the scale to [-1, 1]
  cluster_rows  = TRUE,
  cluster_cols  = FALSE,
  border_color  = NA,
  na_col        = "grey90",
  main          = "ATAC–RNA",
  legend_breaks = c(-1, -0.5, 0, 0.5, 1),cutree_rows = 3,  # nice tick marks)
)
dev.off()


closest_genes$gene_name%in%



library(patchwork)
library(scales)

fmt_mb <- function(x) paste0(round(x/1e6, 2), " Mb")

pics <- list()
for (n in 1:length(closest_genes$gene_name)) {
  # pick a peak you care about (e.g., the one linked to your chosen gene)
p <- StringToGRanges(closest_genes$query_region[n])

# pad generously so the peak isn’t at the edge
p_ext <- Extend(p, upstream = 10000, downstream = 10000)

# p: a single-peak GRanges; p_ext: padded window
pics[[n]] <- CoveragePlot(
  object = ATAC.all$ECs_Cpillary,
  region = p_ext,
  region.highlight = p,
  group.by = "Organ_Subtype",
  tile.size = 100,
  downsample = TRUE,
  annotation = FALSE,  # <- important: no gene track here
  peaks = FALSE,       # <- and no peaks here
  links = FALSE
) &
  scale_x_continuous(labels = fmt_mb, n.breaks = 4) &   # only coverage gets Mb
  theme(
    axis.text.x  = element_text(size = 7, angle = 25, hjust = 1),
    axis.title.x = element_text(size = 8)
  )

peaks_panel <- PeakPlot(
  object = ATAC.all$ECs_Cpillary,
  region = p_ext
) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x  = element_blank(),
    axis.ticks.x = element_blank()
  )

genes_panel <- AnnotationPlot(
  object = ATAC.all$ECs_Cpillary,
  region = p_ext
) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x  = element_blank(),
    axis.ticks.x = element_blank()
  )

# stack them: coverage (styled axis), then peaks, then genes
pics[[n]] <- pics[[n]] / peaks_panel / genes_panel + plot_layout(heights = c(5, 1, 1))
}



library(ggpubr)

sel <- c(5,9,14,19)   # which plots to place
combined <- wrap_plots( pics[sel], ncol = 2, nrow = 2)
pdf("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Projects/Tiantan/Results/Manuscript/Figure2/ECs_Cpillary/ECs_Cpillary.Coverage.pdf",
    width = 6, height = 6) 
print(combined)   # important: actually draw it to the device
dev.off()



#"cell growth involved in cardiac muscle cell development"


# regulation of neuron projection development
Heart_ATAC <- c(ck_sub@compareClusterResult[ck_sub@compareClusterResult$Description=="cell growth involved in cardiac muscle cell development",]$geneID)[1]
Heart_RNA <- c(ck_sub@compareClusterResult[ck_sub@compareClusterResult$Description=="cell growth involved in cardiac muscle cell development",]$geneID)[2]
Heart_ATAC <- unique(trimws(unlist(strsplit(Heart_ATAC, "/"))))
Heart_RNA <- unique(trimws(unlist(strsplit(Heart_RNA, "/"))))
Heart <- intersect(Heart_ATAC,Heart_RNA)


x <- subset(da_peaks.ECs_Cpillary, p_val_adj<0.01)

DefaultAssay(ATAC.all$ECs_Cpillary) <- "Peak.celltype"
closest_genes <- ClosestFeature(ATAC.all$ECs_Cpillary, regions = rownames(x))
closest_genes <- subset(closest_genes, gene_name %in%Heart)


ATAC.all$ECs_Cpillary$Organ_Subtype <- paste0(ATAC.all$ECs_Cpillary$Organ,"_",ATAC.all$ECs_Cpillary$newL3_Subtype.multi.pred_2)
Idents(ATAC.all$ECs_Cpillary) <- "Organ_Subtype"

ATAC.all$ECs_Cpillary <- SortIdents(ATAC.all$ECs_Cpillary)


DefaultAssay(ATAC.all$ECs_Cpillary) <- "Peak.celltype"


fmt_mb <- function(x) paste0(round(x/1e6, 2), " Mb")

pics <- list()
for (n in 1:length(closest_genes$gene_name)) {
  # pick a peak you care about (e.g., the one linked to your chosen gene)
p <- StringToGRanges(closest_genes$query_region[n])

# pad generously so the peak isn’t at the edge
p_ext <- Extend(p, upstream = 10000, downstream = 10000)

# p: a single-peak GRanges; p_ext: padded window
pics[[n]] <- CoveragePlot(
  object = ATAC.all$ECs_Cpillary,
  region = p_ext,
  region.highlight = p,
  group.by = "Organ_Subtype",
  tile.size = 100,
  downsample = TRUE,
  annotation = FALSE,  # <- important: no gene track here
  peaks = FALSE,       # <- and no peaks here
  links = FALSE
) &
  scale_x_continuous(labels = fmt_mb, n.breaks = 4) &   # only coverage gets Mb
  theme(
    axis.text.x  = element_text(size = 7, angle = 25, hjust = 1),
    axis.title.x = element_text(size = 8)
  )

peaks_panel <- PeakPlot(
  object = ATAC.all$ECs_Cpillary,
  region = p_ext
) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x  = element_blank(),
    axis.ticks.x = element_blank()
  )

genes_panel <- AnnotationPlot(
  object = ATAC.all$ECs_Cpillary,
  region = p_ext
) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x  = element_blank(),
    axis.ticks.x = element_blank()
  )

# stack them: coverage (styled axis), then peaks, then genes
pics[[n]] <- pics[[n]] / peaks_panel / genes_panel + plot_layout(heights = c(5, 1, 1))
}




library(ggpubr)

pdf("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Projects/Tiantan/Results/Manuscript/Figure2/ECs_Cpillary/ECs_Cpillary.Coverage.Heart.pdf",
    width = 3, height = 3) 
pics[[1]]
dev.off()

```


```{r ECs_Cpillary,fig.width=8,fig.height=5}


##### Chromvar

Idents(ATAC.all$ECs_Cpillary) <- "Organ"
DefaultAssay(ATAC.all$ECs_Cpillary) <- 'chromvar'

differential.activity <- FindMarkers(
  object = ATAC.all$ECs_Cpillary,
  ident.1 = 'Brain',
  ident.2 = 'Heart',
  only.pos = FALSE,
  mean.fxn = rowMeans,  
  logfc.threshold = 0,
  fc.name = "avg_diff"
)

differential.activity$Motifs <- names(unlist(ATAC.all$ECs_Cpillary@assays$Peak.celltype@motifs@motif.names)[rownames(differential.activity)])  
differential.activity$Motifs.names <- (unlist(ATAC.all$ECs_Cpillary@assays$Peak.celltype@motifs@motif.names)[rownames(differential.activity)])  




# Start from your table:
da <- differential.activity

# Ensure we have a readable label (fall back to motif ID if name missing)
da$label_base <- ifelse(is.na(da$Motifs.names) | da$Motifs.names == "",
                        da$Motifs, da$Motifs.names)

# Protect against p_val_adj == 0 (so -log10 is finite)
da$padj_safe <- ifelse(da$p_val_adj == 0, .Machine$double.xmin, da$p_val_adj)
da$mlog10    <- -log10(da$padj_safe)

# Direction for coloring
da$direction <- ifelse(da$avg_diff > 0, "Brain↑",
                       ifelse(da$avg_diff < 0, "Heart↑", "0"))

# Pick top-10 each side by effect size (use only significant if you want)
sig_cut <- 0.05
da_sig  <- da %>% filter(p_val_adj < sig_cut)

top_up   <- da_sig %>% filter(avg_diff > 0) %>%
  arrange(desc(avg_diff)) %>% slice_head(n = 5)

top_down <- da_sig %>% filter(avg_diff < 0) %>%
  arrange(avg_diff) %>% slice_head(n = 5)

to_label_ids <- c(rownames(top_up), rownames(top_down))

da$label <- ifelse(rownames(da) %in% to_label_ids, da$label_base, "")

# Volcano
vline_x  <- 0
hline_y  <- -log10(sig_cut)

da$direction <- factor(da$direction,levels = c("Heart↑","Brain↑"))
p <- ggplot(da, aes(x = avg_diff, y = mlog10)) +
  geom_point(aes(color = direction), alpha = 0.6, size = 1.4) +
  geom_vline(xintercept = vline_x, linetype = 2) +
  geom_hline(yintercept = hline_y, linetype = 2) +
  scale_color_manual(
    values = c( "Heart↑" = "#2FBF71",  # cool for Heart-enriched
                "Brain↑" = "#3A86FF",  # warm for Brain-enriched
                "0"   = "grey70"),
    breaks = c( "Heart↑","Brain↑"),
    name = NULL
  ) +
  geom_text_repel(
    data = subset(da, label != ""),
    aes(label = label),
    size = 4,
    min.segment.length = 0,
    max.overlaps = Inf,max.time = 1,max.iter = 50000,
    box.padding = 0.5, point.padding = 0.2,segment.size = 0.3,segment.colour = "grey50",
  ) +
  labs(
    x = "Effect size (avg_diff)\n(+ Brain higher, – Heart higher)",
    y = expression(-log[10]("adj. p")),
    title = "Motif activity: Brain vs Heart (ECs_Cpillary)"
  ) +
  theme_classic() +
  theme(legend.position = "top")



pdf("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Projects/Tiantan/Results/Manuscript/Figure2/ECs_Cpillary/ECs_Cpillary.vln.motifs.pdf",height = 3,width = 4.5)
p
dev.off()

x <- subset(differential.activity, p_val_adj<0.01)
x.up.Brain <- x[order(-x$avg_diff  , -x$p_val_adj),][1:12,]
x.down.Heart <- x[order(x$avg_diff, -x$p_val_adj),][1:12,]


mot.brain <- MotifPlot(
  object = ATAC.all$ECs_Cpillary,
  motifs = rownames(x.up.Brain),
  assay = "Peak.celltype"
)+labs(subtitle = "Brain-ECs_Cpillary")

mot.heart <- MotifPlot(
  object = ATAC.all$ECs_Cpillary,
  motifs = rownames(x.down.Heart),
  assay = "Peak.celltype"
)+labs(subtitle = "Heart-ECs_Cpillary")



pdf("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Projects/Tiantan/Results/Manuscript/Figure2/ECs_Cpillary/ECs_Cpillary.motifs.pdf",width = 20, height = 5) 
mot.brain+mot.heart
dev.off()


```



```{r Motif modules,fig.width=5,fig.height=5}

library(dplyr)
library(tibble)
library(ggplot2)
library(ggrepel)
library(RColorBrewer)

## --- 0) Top-50 up + top-50 down (you already have this) ---
top_up   <- da_sig %>% filter(avg_diff > 0) %>% arrange(desc(avg_diff)) %>% slice_head(n = 50)
top_down <- da_sig %>% filter(avg_diff < 0) %>% arrange(avg_diff)         %>% slice_head(n = 50)

avg.motif <- as.data.frame(
  AverageExpression(ATAC.all$ECs_Cpillary,
                    features = c(top_up$Motifs, top_down$Motifs),
                    group.by = "Organ")$chromvar
)
avg.motif$Organ <- ifelse(rownames(avg.motif) %in% top_up$Motifs, "Brain", "Heart")
avg.motif$Brain <- log10(avg.motif$Brain + 1)
avg.motif$Heart <- log10(avg.motif$Heart + 1)

## --- 1) Motif → pretty name → family mapping ---
motif_names <- da %>% select(Motifs, Motifs.names) %>% distinct()

# Expand the family patterns a bit to cover your 100 picks
family_patterns <- c(
  "AP-1 (FOS/JUN/BATF)" = "^(FOS|FOSB|FOSL1|FOSL2|JUN|JUNB|JUND|BATF|JDP2)(::|$)",
  "TCF/LEF"             = "^(TCF7L2|TCF7L1|TCF7|TCF4|TCF3|LEF1)$",
  "SNAIL"               = "^SNAI[123]$",
  "SOX"                 = "^SOX[0-9A-Z]+$",
  "ETS (ETV/ELF/EHF/GABPA)" = "^(ETV1|ETV2|ETV4|ELF1|ELF3|ELF5|EHF|GABPA)$",
  "FOX"                 = "^FOX[A-Z0-9]+$",
  "IKAROS (IKZF)"       = "^IKZF[0-9]+$",
  "BACH/NFE2/MAF"       = "^(BACH[0-9]+|NFE2(L1)?|MAF(::NFE2)?)$",
  "GATA"                = "^GATA[1-6]$",
  "TEAD"                = "^TEAD[1-4]$",
  "NFAT"                = "^NFATC[0-9]+$",
  "NFI"                 = "^NFI[ABCX]|^NFIX|^NFIB|^NFIC",
  "bHLH (MYF/MYOG/ASCL/TAL)" = "^(MYF5|MYOG|ASCL1|TAL1)",
  "ZEB/ZBTB"            = "^(ZEB[12]|ZBTB18)$",
  "TWIST/SRY/bHLH"      = "^(TWIST1|SRY)$"
)

assign_family <- function(x) {
  nm <- x
  for (fam in names(family_patterns)) {
    if (grepl(family_patterns[[fam]], nm, perl = TRUE)) return(fam)
  }
  "Other"
}

avg_labeled <- avg.motif %>%
  rownames_to_column("Motifs") %>%
  left_join(motif_names, by = "Motifs") %>%
  mutate(name   = ifelse(is.na(Motifs.names) | Motifs.names == "", Motifs, Motifs.names),
         family = vapply(name, assign_family, character(1)))

avg_labeled <- avg_labeled[avg_labeled$family != "AP-1 (FOS/JUN/BATF)",]

## --- 2) Choose one label position per family (most Brain-vs-Heart distinct) ---
label_once <- avg_labeled %>%
  group_by(family) %>%
  slice_max(order_by = abs(Brain - Heart), n = 1, with_ties = FALSE) %>%
  ungroup()

## --- 3) Palette (one colour per present family) ---
fam_levels <- sort(unique(avg_labeled$family))
fam_cols   <- setNames(colorRampPalette(brewer.pal(8, "Dark2"))(length(fam_levels)),
                       fam_levels)




## --- 4) Plot Brain vs Heart with family colour + organ shape ---
p_top100 <- ggplot(avg_labeled, aes(x = Brain, y = Heart, colour = family, shape = Organ)) +
  geom_point(size = 2.2, alpha = 0.9) +
  # optional: faint ellipses per family (comment out if you don't want them)
  # stat_ellipse(aes(group = family), level = 0.65, linewidth = 0.3, alpha = 0.25, show.legend = FALSE) +
  geom_text_repel(
    data = label_once,
    aes(label = family, colour = family),
    size = 0, fontface = "bold",
    box.padding = 0.25, point.padding = 0.15,
    min.segment.length = 0, segment.size = 0.25, segment.color = "grey70",
    max.overlaps = Inf, show.legend = FALSE
  ) +
  geom_abline(slope = 1, intercept = 0, linetype = "22", linewidth = 0.4, colour = "grey65") +
  scale_color_manual(values = fam_cols, name = "Motif family") +
  scale_shape_manual(values = c(Brain = 16, Heart = 17), name = "Organ") +
  coord_cartesian(xlim = c(-0.1, 12), ylim = c(-0.1, 12)) +
  labs(x = "Brain (log10 avg chromVAR + 1)", y = "Heart (log10 avg chromVAR + 1)") +
  theme_classic(base_size = 12) +
  theme(
    axis.title = element_text(face = "bold"),
    axis.text  = element_text(color = "grey20"),
    panel.grid.major = element_line(color = "grey92", linewidth = 0.3),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "white", color = NA),
    legend.position = "right",
    legend.title = element_text(face = "bold"),
    legend.key.height = unit(0.4, "cm"),
    legend.key.width  = unit(0.5, "cm"),
    plot.margin = margin(6, 10, 6, 6)
  ) +
  guides(
    colour = guide_legend(override.aes = list(size = 3, alpha = 1), ncol = 1),
    shape  = guide_legend(override.aes = list(size = 3, alpha = 1), ncol = 1)
  )


pdf("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Projects/Tiantan/Results/Manuscript/Figure2/ECs_Cpillary/ECs_Cpillary.motifs.scatter.pdf",width = 8, height = 6) 

p_top100

dev.off()


```



```{r Motif subtypes,fig.width=15,fig.height=20}



ATAC.all$ECs_Cpillary$Organ_subtypes <- paste0(ATAC.all$ECs_Cpillary$Organ,"_",ATAC.all$ECs_Cpillary$newL3_Subtype.multi.pred_2)

differential.activity <- FindAllMarkers(
  object = ATAC.all$ECs_Cpillary,
  group.by = "Organ_subtypes",
  only.pos = FALSE,
  logfc.threshold = 0
)

differential.activity$Motifs <- names(unlist(ATAC.all$ECs_Cpillary@assays$Peak.celltype@motifs@motif.names)[differential.activity$gene])  
differential.activity$Motifs.names <- (unlist(ATAC.all$ECs_Cpillary@assays$Peak.celltype@motifs@motif.names)[differential.activity$gene])  


top5.motifs <- c()
for (clusters in unique(differential.activity$cluster)) {
  x <- subset(differential.activity, cluster == clusters )
  x <- x[order(-x$avg_log2FC, -x$p_val_adj),][1:5,]
  top5.motifs <- rbind(top5.motifs,x)
}



top.motif.avg <- as.data.frame(AverageExpression(ATAC.all$ECs_Cpillary,assays = "chromvar",unique(top5.motifs$Motifs),group.by = c("Organ_subtypes"))$chromvar)

top.motif.avg$mot.name <- top5.motifs[top5.motifs$Motifs%in%rownames(top.motif.avg),]$Motifs.names
rownames(top.motif.avg) <- paste0(unique(top.motif.avg$mot.name),"(",rownames(top.motif.avg),")")
top.motif.avg <- top.motif.avg[,-7]

col_info_atac <- tibble(col = colnames(top.motif.avg)) %>%
  separate(col, into = c("Region"), sep = "-", remove = FALSE) %>%
  arrange(Region)
top.motif.avg <- top.motif.avg[, col_info_atac$col, drop = FALSE]

ann_atac <- col_info_atac %>%
  dplyr::select(Region) %>%
  as.data.frame()
rownames(ann_atac) <- col_info_atac$col

region_cols <- c(Brain = "#3A86FF", Heart = "#2FBF71")

library(ggplotify)   # as.ggplot()
p1 <- as.ggplot(pheatmap(
  top.motif.avg,
  cluster_rows = TRUE, cluster_cols = TRUE, scale = "row",
  color = colorRampPalette(c("grey40","white","purple3"))(100),
  annotation_col = ann_atac,
  annotation_colors = list(Region = region_cols),
  fontsize_row = 12, fontsize_col = 12,
  main = "ATAC_ECs_Cpillary",labels_col =  sub("^[^-]*-", "", colnames(top.motif.avg))
))+labs(subtitle = "Motif activity")

pdf("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Projects/Tiantan/Results/Manuscript/Figure2/ECs_Cpillary/ECs_Cpillary.motifs.subtype.pdf",width = 6, height = 8) 
 p1
dev.off()


```

