---
title: "DataIntegration"
output: html_document
date: "2025-04-04"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo                  = FALSE
                      ,warning              = FALSE
                      ,message              = FALSE
                      ,error                = TRUE
                      ,dev                  = c('png','pdf')
                      ,pdf.options(encoding = "ISOLatin9.enc", useKerning=FALSE, useDingbats=FALSE))
.libPaths("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Rloading/4.4/")

```


A report by **Elyas.Mohammadi**


```{r libraries}

library(Seurat)
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(patchwork)
library(clusterProfiler)
library(org.Hs.eg.db)
library(AnnotationHub)
library(EnsDb.Hsapiens.v86)
library(harmony)
library(ggthemes)
library(viridis)
library(dplyr)

library(ggh4x)
axis <- ggh4x::guide_axis_truncated(
  trunc_lower = unit(0, "npc"),
  trunc_upper = unit(1.5, "cm"))

```


# Loading datasets scRNA 


```{r Load,fig.width=30,fig.height=30}

############################
## In house generated data
############################


scRNA <- readRDS("../Rsave/OMIX008302-02.rds")
Metadata_ENatlas_all <- read.delim("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Projects/Tiantan/Rsave/Metadata_ENatlas_all.txt")
scRNA@meta.data <- Metadata_ENatlas_all[match(rownames(Metadata_ENatlas_all),rownames(scRNA@meta.data)),]

###############################################
## Sten's lab data (Nat2024) (only vasculature)
###############################################

scRNA.Sten <- readRDS("../Rsave/Subset_97_122.RNA.Rds")
scRNA.Sten[["RNA"]] <- scRNA.Sten[["originalexp"]]
scRNA.Sten@assays$originalexp <- NULL  # Remove the old name (optional)
DefaultAssay(scRNA.Sten) <- "RNA"
scRNA.Sten <- subset(scRNA.Sten,ClusterName != "Gbl_late")
scRNA.Sten <- NormalizeData(scRNA.Sten)
scRNA.Sten <- FindVariableFeatures(scRNA.Sten)
scRNA.Sten <- ScaleData(scRNA.Sten)
scRNA.Sten <- RunPCA(scRNA.Sten)


###################################
## Sten's lab metadata correction
###################################

round_down_05 <- function(x) {
  floor(x + 1e-8) + as.numeric(x %% 1 > 0.5)
}
scRNA.Sten$Age.decimal <- round_down_05(scRNA.Sten$Age)
scRNA.Sten$Age <- round_down_05(scRNA.Sten$Age)

scRNA.Sten$Age.GW <- paste0("GW",scRNA.Sten$Age+2)
scRNA.Sten$Age.PCW <- paste0("PCW",scRNA.Sten$Age)
scRNA.Sten$Age.GW <- gsub("GW8","GW08",scRNA.Sten$Age.GW)
scRNA.Sten$Age.GW <- gsub("GW9","GW09",scRNA.Sten$Age.GW)


scRNA$Age.GW <- scRNA$Age
scRNA$Age.PCW <- as.numeric(gsub("GW","",scRNA$Age.GW))-2
scRNA$Age.PCW <- paste0("PCW",scRNA$Age.PCW)

scRNA.Sten$Age.PCW <- gsub("PCW6","PCW06",scRNA.Sten$Age.PCW)
scRNA.Sten$Age.PCW <- gsub("PCW7","PCW07",scRNA.Sten$Age.PCW)
scRNA.Sten$Age.PCW <- gsub("PCW8","PCW08",scRNA.Sten$Age.PCW)
scRNA.Sten$Age.PCW <- gsub("PCW9","PCW09",scRNA.Sten$Age.PCW)

scRNA$Age.PCW <- gsub("PCW4","PCW04",scRNA$Age.PCW)
scRNA$Age.PCW <- gsub("PCW5","PCW05",scRNA$Age.PCW)
scRNA$Age.PCW <- gsub("PCW6","PCW06",scRNA$Age.PCW)
scRNA$Age.PCW <- gsub("PCW7","PCW07",scRNA$Age.PCW)
scRNA$Age.PCW <- gsub("PCW8","PCW08",scRNA$Age.PCW)
scRNA$Age.PCW <- gsub("PCW9","PCW09",scRNA$Age.PCW)

scRNA$Dataset <- "Generated"
scRNA.Sten$Dataset <- "Mannens.Nat2024"


####################################################
## In house generated data extracting the vasculature
####################################################

"%Nin%" <- Negate("%in%")
scRNA.vasc <- subset(scRNA, newL2_Cell_type %in% c("ECs","Mural")& L3_Cell_type %Nin% c("Debri","Doublet","Sinus Venosus"))
scRNA.vasc <- FindVariableFeatures(scRNA.vasc)
scRNA.vasc <- ScaleData(scRNA.vasc)
scRNA.vasc <- RunPCA(scRNA.vasc)

save(scRNA.vasc,scRNA.Sten,file = "./Vasc.datasets.Rdata")
saveRDS(scRNA,"./OMIX008302-02.edited.rds")

```


```{r Load,fig.width=30,fig.height=30}

####################################################
#     Label transferring from inhouse to Sten's data      
####################################################

load("./Vasc.datasets.Rdata")
scRNA.vasc.brain <- subset(scRNA.vasc,Organ=="Brain")
scRNA.vasc.brain <- FindVariableFeatures(scRNA.vasc.brain)
scRNA.vasc.brain <- ScaleData(scRNA.vasc.brain)
scRNA.vasc.brain <- RunPCA(scRNA.vasc.brain)
  


Label.transfer <- function(set, qurey, annotation){
  # Finding anchors
  SP1.anchors.log <- FindTransferAnchors(
    reference = set, 
    query = qurey, 
    normalization.method = "LogNormalize",
    reference.assay = "RNA",
    query.assay = "RNA"
  )

  # Transfer labels from reference metadata
  SP1.predictions <- TransferData(
    anchorset = SP1.anchors.log,
    refdata = set[[annotation, drop = TRUE]],  
    weight.reduction = qurey[["pca"]],
    dims = 1:20
  )

  # Add to query metadata
  qurey[[annotation]] <- SP1.predictions$predicted.id
  return(qurey)
}


options(future.globals.maxSize = 128000 * 1024^2)  # Set maximum size to 64 GB
scRNA.Sten <- Label.transfer(scRNA.vasc.brain,scRNA.Sten,"newL2_Cell_type")
scRNA.Sten <- Label.transfer(scRNA.vasc.brain,scRNA.Sten,"newL3_Cell_type")
scRNA.Sten <- Label.transfer(scRNA.vasc.brain,scRNA.Sten,"newL3_Subtype")

scRNA.Sten <- RunUMAP(scRNA.Sten,dims = 1:30)
save(scRNA.vasc,scRNA.Sten,file = "./Vasc.datasets.Rdata")


```




```{r Dims,fig.width=30,fig.height=30}

####################################################
#     CCA data integration     
####################################################


load("./Vasc.datasets.Rdata")

scRNA.Sten$Batch <- scRNA.Sten$Method
scRNA.Sten$Organ <- "Brain"

RNA.int <- merge(scRNA.vasc,scRNA.Sten)
rm(scRNA.vasc,scRNA.Sten)
gc()

RNA.int <- SplitObject(RNA.int, split.by = "Batch")

# normalize and identify variable features for each dataset independently
RNA.int <- lapply(X = RNA.int, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

# select features that are repeatedly variable across datasets for integration
features <- SelectIntegrationFeatures(object.list = RNA.int)
anchors <- FindIntegrationAnchors(object.list = RNA.int, anchor.features = features)
RNA.int <- IntegrateData(anchorset = anchors)
# Run the standard workflow for visualization and clustering
RNA.int <- ScaleData(RNA.int, verbose = FALSE)

DefaultAssay(RNA.int) <- "integrated"
RNA.int <- RunPCA(RNA.int, npcs = 50, verbose = FALSE)
RNA.int <- RunUMAP(RNA.int, reduction = "pca", dims = 1:30)
 

```



```{r Dims,fig.width=20,fig.height=10}

####################################################
#     Harmony data integration     
####################################################

DefaultAssay(RNA.int) <- "RNA"
RNA.int <- NormalizeData(RNA.int,assay = "RNA")
RNA.int <- FindVariableFeatures(RNA.int,nfeatures = 3000,assay = "RNA")
RNA.int <- ScaleData(RNA.int,assay = "RNA")

RNA.int <- RunPCA(RNA.int,assay = "RNA",reduction.name = "pca_harmony")

RNA.int <- RunHarmony(RNA.int,
  group.by.vars=c("Batch"),
  reduction.use = "pca_harmony",
  dims.use = 1:30,
  verbose = TRUE,
  reduction.save = "harmony",
  project.dim = TRUE,max_iter = 30)


ElbowPlot(RNA.int,ndims = 30,reduction = "harmony")
RNA.int <- RunUMAP(RNA.int,reduction = "harmony",dims = 1:26,reduction.name = "umap_harmony")


saveRDS(RNA.int,"./RNA.int.Rds")
```


```{r Dims,fig.width=20,fig.height=10}


########################
#     color Schemes     
########################


all_colors <- c(
  # Endothelial (blue → violet scale)
  "ECs_Arterial"      = "#A6CEE3",  # light blue
  "ECs_Cpillary"      = "#1F78B4",  # medium blue
  "ECs_Lymphatic"     = "#6A3D9A",  # deep violet
  "ECs_Mitotic"       = "#9E9AC8",  # lavender
  "ECs_Venous"        = "purple",  # indigo

  # Special endothelial identities (greens)
  "Endocardial-like"  = "#33A02C",  # distinct green
  "Tip cells"         = "#66C2A5",  # minty green

"Mural_Fibroblasts" = "#FFD700",  # goldenrod (brighter and more saturated than gold1)
"Mural_Mitotic"     = "orange2",  # dark orange
"Mural_Pericytes"   = "#E6550D",  # brick orange
"Mural_Precursors"  = "#B22222",  # firebrick
"Mural_SMCs"        = "#8B4513"   # saddle brown (rich and dark)
)

organ_colors <- c(
  "Brain" = "#4C72B0",  # Slate Blue
  "Heart" = "#D55E00"   # Burnt Sienna
)

age_colors <- c(
  "GW06" = "#d73027",  # deep red
  "GW07" = "#f46d43",
  "GW08" = "#fdae61",
  "GW09" = "#fee08b",
  "GW10" = "#e0f3f8",
  "GW11" = "#abd9e9",
  "GW12" = "#74add1",
  "GW14" = "#4575b4",
  "GW15" = "#313695",
  "GW24" = "#2c104d"   # deep blue-violet
)


```


```{r Dims,fig.width=20,fig.height=10}

####################################################
#     Dimplots of integrated object     
####################################################

RNA.int <- readRDS("./RNA.int.Rds")
RNA.int$newL3_Cell_type <- factor(RNA.int$newL3_Cell_type,levels = c("Mural_SMCs","Mural_Precursors" , "Mural_Pericytes","Mural_Mitotic", "Mural_Fibroblasts" ,"Endocardial-like", "Tip cells",  "ECs_Lymphatic","ECs_Venous"  ,"ECs_Mitotic" ,"ECs_Cpillary","ECs_Arterial" ))


p1 <- DimPlot(RNA.int,group.by = "newL2_Cell_type",label = T,repel = T,reduction = "umap_harmony")+ggtitle("Harmony-L2celltype")+
 guides(x = axis, y = axis) +xlab("UMAP 1")+ylab("UMAP 2")+
  theme(axis.line = element_line(arrow = arrow(angle = 20, length = unit(4, "points"))),
        axis.title = element_text(hjust = 0,size = 10),axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank())


p2 <- DimPlot(RNA.int,group.by = "newL2_Cell_type",label = T,repel = T)+ggtitle("CCA-L2celltype")+
 guides(x = axis, y = axis) +xlab("UMAP 1")+ylab("UMAP 2")+
  theme(axis.line = element_line(arrow = arrow(angle = 20, length = unit(4, "points"))),
        axis.title = element_text(hjust = 0,size = 10),axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank())

pdf("../Results/Manuscript/2.Integration.pdf",width = 8,height = 4)
p1+p2
dev.off()

p3 <- DimPlot(RNA.int,group.by = "newL3_Cell_type",label = F,repel = T,reduction = "umap_harmony",cols = all_colors)+ggtitle("Harmony-L3celltype")+
 guides(x = axis, y = axis) +xlab("UMAP 1")+ylab("UMAP 2")+
  theme(axis.line = element_line(arrow = arrow(angle = 20, length = unit(4, "points"))),
        axis.title = element_text(hjust = 0,size = 10),axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank())


p4 <- DimPlot(RNA.int,group.by = "newL3_Cell_type",label = F,repel = T,cols = all_colors)+ggtitle("CCA-L3celltype")+
 guides(x = axis, y = axis) +xlab("UMAP 1")+ylab("UMAP 2")+
  theme(axis.line = element_line(arrow = arrow(angle = 20, length = unit(4, "points"))),
        axis.title = element_text(hjust = 0,size = 10),axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank())


pdf("../Results/Manuscript/3.Integration.pdf",width = 12,height = 4)
p3+p4
dev.off()

```



## All 

```{r Dims2,fig.width=15,fig.height=10}


####################################################################
# GO analysis of cross organ comparison between vasculature subtypes     
####################################################################

"%Nin%" <- Negate("%in%")

RNA.int$Organ_L3_Cell_type <- paste0(RNA.int$Organ,"_",RNA.int$newL3_Cell_type)

RNA.int <- SetIdent(RNA.int,value = "Organ_L3_Cell_type")

library(MAST)
# ECs_Arterial <- FindMarkers(RNA.int,ident.1 = "Brain_ECs_Arterial",ident.2 = "Heart_ECs_Arterial",logfc.threshold = 0.5,densify = T,test.use = "MAST")
# ECs_Cpillary <- FindMarkers(RNA.int,ident.1 = "Brain_ECs_Cpillary",ident.2 = "Heart_ECs_Cpillary",logfc.threshold = 0.5,densify = T,test.use = "MAST")
# ECs_Lymphatic <- FindMarkers(RNA.int,ident.1 = "Brain_ECs_Lymphatic",ident.2 = "Heart_ECs_Lymphatic",logfc.threshold = 0.5,densify = T,test.use = "MAST")
# ECs_Mitotic <- FindMarkers(RNA.int,ident.1 ="Brain_ECs_Mitotic" ,ident.2 = "Heart_ECs_Mitotic",logfc.threshold = 0.5,densify = T,test.use = "MAST")
# ECs_Venous <- FindMarkers(RNA.int,ident.1 ="Brain_ECs_Venous" ,ident.2 = "Heart_ECs_Venous",logfc.threshold = 0.5,densify = T,test.use = "MAST")
# Endocardial.like <- FindMarkers(RNA.int,ident.1 ="Brain_Endocardial-like" ,ident.2 = "Heart_Endocardial-like",logfc.threshold = 0.5,densify = T,test.use = "MAST")
# Mural_Fibroblasts <- FindMarkers(RNA.int,ident.1 = "Brain_Mural_Fibroblasts",ident.2 = "Heart_Mural_Fibroblasts",logfc.threshold = 0.5,densify = T,test.use = "MAST")
# Mural_Mitotic <- FindMarkers(RNA.int,ident.1 = "Brain_Mural_Mitotic",ident.2 = "Heart_ECs_Mitotic",logfc.threshold = 0.5,densify = T,test.use = "MAST")
# Mural_Pericytes <- FindMarkers(RNA.int,ident.1 ="Brain_Mural_Pericytes" ,ident.2 ="Heart_Mural_Pericytes" ,logfc.threshold = 0.5,densify = T,test.use = "MAST")
# Mural_Precursors <- FindMarkers(RNA.int,ident.1 = "Brain_Mural_Precursors",ident.2 = "Heart_Mural_Precursors",logfc.threshold = 0.5,densify = T,test.use = "MAST")
# Mural_SMCs <- FindMarkers(RNA.int,ident.1 = "Brain_Mural_SMCs" ,ident.2 = "Heart_Mural_SMCs",logfc.threshold = 0.5,densify = T,test.use = "MAST")
# Tip.cells <- FindMarkers(RNA.int,ident.1 = "Brain_Tip cells",ident.2 = "Heart_Tip cells",logfc.threshold = 0.5,densify = T,test.use = "MAST")
# 
# save(ECs_Arterial,ECs_Cpillary,ECs_Lymphatic,ECs_Mitotic,ECs_Venous,Endocardial.like,Mural_Fibroblasts,Mural_Mitotic,Mural_Pericytes,Mural_Precursors,Mural_SMCs,Tip.cells,file = "../Rsave/L3.Organ.Degs.int.Rdata")

load("../Rsave/L3.Organ.Degs.int.Rdata")

ECs_Arterial$cluster <- "ECs_Arterial" 
ECs_Cpillary$cluster <- "ECs_Cpillary" 
ECs_Lymphatic$cluster <- "ECs_Lymphatic" 
ECs_Mitotic$cluster <- "ECs_Mitotic" 
ECs_Venous$cluster <- "ECs_Venous" 
Endocardial.like$cluster <- "Endocardial.like" 
Mural_Fibroblasts$cluster <- "Mural_Fibroblasts" 
Mural_Mitotic$cluster <- "Mural_Mitotic" 
Mural_Pericytes$cluster <- "Mural_Pericytes" 
Mural_Precursors$cluster <- "Mural_Precursors" 
Mural_SMCs$cluster <- "Mural_SMCs" 
Tip.cells$cluster <- "Tip.cells" 


ECs_Arterial$gene <- rownames(ECs_Arterial)
ECs_Cpillary$gene <- rownames(ECs_Cpillary)
ECs_Lymphatic$gene <- rownames(ECs_Lymphatic)
ECs_Mitotic$gene <- rownames(ECs_Mitotic) 
ECs_Venous$gene <- rownames(ECs_Venous) 
Endocardial.like$gene <- rownames(Endocardial.like) 
Mural_Fibroblasts$gene <- rownames(Mural_Fibroblasts)
Mural_Mitotic$gene <- rownames(Mural_Mitotic)
Mural_Pericytes$gene <- rownames(Mural_Pericytes) 
Mural_Precursors$gene <- rownames(Mural_Precursors) 
Mural_SMCs$gene <- rownames(Mural_SMCs) 
Tip.cells$gene <- rownames(Tip.cells) 

DEGs <- do.call(rbind,list(ECs_Arterial,ECs_Cpillary,ECs_Lymphatic,ECs_Mitotic,ECs_Venous,Endocardial.like,Mural_Fibroblasts,Mural_Mitotic,Mural_Pericytes,Mural_Precursors,Mural_SMCs,Tip.cells))


tops <- c()
for (clusters in unique(DEGs$cluster)) {
  x <- subset(DEGs, cluster == clusters & p_val_adj<0.05)
  x <- x[order(-x$avg_log2FC, -x$p_val_adj),][1:50,]
  tops <- rbind(tops,x)
}


### GO
GO.terms <- list()
for (clusters in na.omit(unique(tops$cluster))) {
GO.up <- enrichGO(gene = na.omit(unique(tops[tops$cluster==clusters,]$gene)),
                   OrgDb = org.Hs.eg.db,
                   keyType = "SYMBOL",
                   ont = "BP",
                   pAdjustMethod = "BH",
                   pvalueCutoff = 0.05,
                   qvalueCutoff = 0.05)
GO.up@result$Padj <- -log10(GO.up@result$p.adjust)
  GO.terms[[paste0(clusters)]] <- GO.up
  }

tops.down <- c()
for (clusters in unique(DEGs$cluster)) {
  x <- subset(DEGs, cluster == clusters & p_val_adj<0.05)
  x <- x[order(x$avg_log2FC, -x$p_val_adj),][1:50,]
  tops.down <- rbind(tops.down,x)
}



### GO
GO.terms.down <- list()
for (clusters in na.omit(unique(tops.down$cluster))) {
GO.up <- enrichGO(gene = na.omit(unique(tops.down[tops.down$cluster==clusters,]$gene)),
                   OrgDb = org.Hs.eg.db,
                   keyType = "SYMBOL",
                   ont = "BP",
                   pAdjustMethod = "BH",
                   pvalueCutoff = 0.05,
                   qvalueCutoff = 0.05)
GO.up@result$Padj <- -log10(GO.up@result$p.adjust)
  GO.terms.down[[paste0(clusters)]] <- GO.up
  }



# Top GO Pathways
pathways <- c()
for (clusters in GO.terms) {
  clusters@result <- subset(clusters@result,qvalue<0.05)
 x <-  clusters@result$Description[1:5]
 pathways <- c(pathways,x)
  
}


pathways2 <- c()
for (clusters in GO.terms.down) {
  clusters@result <- subset(clusters@result,qvalue<0.05)
 x <-  clusters@result$Description[1:5]
 pathways2 <- c(pathways2,x)
  
}





# Create an empty data frame to store the results
result_df <- matrix(0, nrow = length(unique(pathways)), ncol = length(GO.terms))
rownames(result_df) <- unique(pathways)
colnames(result_df) <- names(GO.terms)

# Loop through each cluster in PF.GO and extract Padj values
for (cluster_name in names(GO.terms)) {
  cluster_df <- GO.terms[[cluster_name]]@result # Access the result section
  for (term in pathways) {
    if (term %in% cluster_df$Description) {
      result_df[term, cluster_name] <- cluster_df$Padj[cluster_df$Description == term]
    }
  }
}

result_df <- as.data.frame(result_df) # Ensure `result_df` is a data frame with numeric values
result_df[] <- lapply(result_df, as.numeric) # Convert all columns to numeric



result_df2 <- matrix(0, nrow = length(unique(pathways2)), ncol = length(GO.terms.down))
rownames(result_df2) <- unique(pathways2)
colnames(result_df2) <- names(GO.terms.down)

# Loop through each cluster in PF.GO and extract Padj values
for (cluster_name in names(GO.terms.down)) {
  cluster_df <- GO.terms.down[[cluster_name]]@result # Access the result section
  for (term in pathways2) {
    if (term %in% cluster_df$Description) {
      result_df2[term, cluster_name] <- cluster_df$Padj[cluster_df$Description == term]
    }
  }
}

result_df2 <- as.data.frame(result_df2) # Ensure `result_df` is a data frame with numeric values
result_df2[] <- lapply(result_df2, as.numeric) # Convert all columns to numeric


library(pheatmap)

pdf("../Results/Brain.Up.int(top5).pdf",width = 9,height = 10)
# Create a heatmap
pheatmap(
  mat = result_df,
  cluster_rows = TRUE,          # Cluster rows (CSC terms)
  cluster_cols = TRUE,          # Cluster columns (clusters)
  scale = "none",               # Don't scale the data
  color = colorRampPalette(c("white", "red"))(50), # Custom color palette
  main = "Upregulated GO pathways in Brain vs Heart",   # Title
  display_numbers = TRUE,       # Display numbers in cells
  fontsize_number = 8           # Adjust font size of numbers
)
dev.off()



pdf("../Results/Heart.Up.int(top5).pdf",width = 9,height = 10)
# Create a heatmap
pheatmap(
  mat = result_df2,
  cluster_rows = TRUE,          # Cluster rows (CSC terms)
  cluster_cols = TRUE,          # Cluster columns (clusters)
  scale = "none",               # Don't scale the data
  color = colorRampPalette(c("white", "red"))(50), # Custom color palette
  main = "Upregulated GO pathways in Heart vs Brain",   # Title
  display_numbers = TRUE,       # Display numbers in cells
  fontsize_number = 8           # Adjust font size of numbers
)
dev.off()

write.csv(DEGs,"../Results/Brain.vs.Heart.int.csv")
write.csv(tops,"../Results/Brain.Up_top50.int.csv")
write.csv(tops.down,"../Results/Heart.Up_top50.int.csv")


```

```{r Dims2,fig.width=15,fig.height=30}

####################################################
#    VLN plot of cross organ comparison     
####################################################

tops$cluster <- gsub("Endocardial.like","Endocardial-like",tops$cluster)
tops$cluster <- gsub("Tip.cells","Tip cells",tops$cluster)
clusters <- unique(tops$cluster)
tops.down$cluster <- gsub("Endocardial.like","Endocardial-like",tops.down$cluster)
tops.down$cluster <- gsub("Tip.cells","Tip cells",tops.down$cluster)

pics <- list()
for (cl in clusters) {
top5.brain <- tops %>%
  filter(cluster == cl) %>%
  arrange(desc(avg_log2FC)) %>%
  slice_head(n = 5) %>%
  mutate(direction = "Brain")

top5.heart <- tops.down %>%
  filter(cluster == cl) %>%
  arrange(avg_log2FC) %>%
  slice_head(n = 5) %>%
  mutate(direction = "Heart")

top10 <- rbind(top5.brain, top5.heart)
genes_to_plot <- top10$gene

  subset_obj <- subset(RNA.int, idents = c(paste0("Brain_", cl), paste0("Heart_", cl)))

  p <- VlnPlot(subset_obj, features = genes_to_plot, group.by = "newL3_Cell_type",split.by = "Organ",split.plot = TRUE, pt.size = 0, ncol = 10,cols = organ_colors)&ylab("")&xlab("") &
    theme_minimal(base_size = 14) &
    theme(
        strip.text = element_text(size = 13, face = "bold"),
        axis.text.x = element_text(size=12,angle = 30),
        axis.text.y = element_text(size = 10,),
        axis.ticks = element_blank(),
        plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
        panel.spacing = unit(1, "lines"),
        panel.grid.major = element_blank()
    ) &NoLegend()
  pics[[cl]] <- p
#   ggsave(filename = paste0("../Results/VlnPlot_", cl, ".pdf"), plot = p, width = 6, height = 8)
 }



pdf("../Results/Manuscript/VLN.cross.organ.pdf",width = 15,height = 30)
wrap_plots(pics,ncol = 1)
dev.off()

```






```{r Dims2,fig.width=15,fig.height=10}

###########################
#     Proportion plots     
###########################

# Create 3-way table
tab <- table(RNA.int$newL1_Cell_type,RNA.int$newL2_Cell_type,RNA.int$newL3_Cell_type, RNA.int$Organ, RNA.int$Age.GW)

# Convert to data frame
df <- as.data.frame(tab)
colnames(df) <- c("All","Celltype","Cellsubtype", "Organ", "Age.GW", "Count")

df$Cellsubtype <- factor(df$Cellsubtype,levels = c(EC_subtypes,Mural_subtypes))
# Compute proportions within each Celltype * Experiment group

df.brain <- subset(df,Organ=="Brain")
df.heart <- subset(df,Organ=="Heart")

df.brain <- df.brain %>%
  group_by(All, Age.GW) %>%
  mutate(Proportion = Count / sum(Count))

df.heart <- df.heart %>%
  group_by(All, Age.GW) %>%
  mutate(Proportion = Count / sum(Count))

# Plot with facets for experiments

df.brain.rm <- subset(df.brain,Age.GW%Nin%c("GW11","GW15"))
df.heart.rm <- subset(df.heart,Age.GW%Nin%c("GW11","GW15"))


# Improved version
p1 <- ggplot(df.brain.rm, aes(x = Age.GW, y = Proportion, fill = Cellsubtype)) +
  geom_bar(stat = "identity", width = 50, color = "white", size = .5) +
  facet_wrap(~ Age.GW, scales = "free_x",ncol = 10) +
  scale_fill_manual(values = all_colors)+
  labs(
    title = "Brain",
    subtitle = "",
    x = NULL,
    y = "Proportion",
    fill = "Cellsubtype"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 12, color = "gray30"),
    axis.text.x = element_text(angle = 90, hjust = 1, size = 12,face = "bold"),
    axis.text.y = element_text(size = 11),
    legend.title = element_text(face = "bold"),
    legend.position = "right",
    strip.text = element_text(face = "bold", size = 0),
    panel.spacing = unit(.1, "lines"),
    panel.grid.major.x = element_blank()
  ) +
  guides(fill = guide_legend(override.aes = list(size = 4)))


# Improved version
p2 <- ggplot(df.heart.rm, aes(x = Age.GW, y = Proportion, fill = Cellsubtype)) +
  geom_bar(stat = "identity", width = 50, color = "white", size = .5) +
  facet_wrap(~ Age.GW, scales = "free_x",ncol = 10) +
  scale_fill_manual(values = all_colors)+
  labs(
    title = "Heart",
    subtitle = "",
    x = NULL,
    y = "Proportion",
    fill = "Cellsubtype"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 12, color = "gray30"),
    axis.text.x = element_text(angle = 90, hjust = 1, size = 12,face = "bold"),
    axis.text.y = element_text(size = 11),
    legend.title = element_text(face = "bold"),
    legend.position = "right",
    strip.text = element_text(face = "bold", size = 0),
    panel.spacing = unit(.1, "lines"),
    panel.grid.major.x = element_blank()
  ) +
  guides(fill = guide_legend(override.aes = list(size = 4)))


pdf("../Results/Manuscript/RNA.proportions(version1).pdf",width = 6,height = 10)
p1/p2
dev.off()



pdf("../Results/Manuscript/RNA.proportions(onlyBrain).pdf",width = 6,height = 5)

ggplot(df.brain, aes(x = Age.GW, y = Proportion, fill = Cellsubtype)) +
  geom_bar(stat = "identity", width = 50, color = "white", size = .5) +
  facet_wrap(~ Age.GW, scales = "free_x",ncol = 10) +
  scale_fill_manual(values = all_colors)+
  labs(
    title = "Brain",
    subtitle = "",
    x = NULL,
    y = "Proportion",
    fill = "Cellsubtype"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 12, color = "gray30"),
    axis.text.x = element_text(angle = 90, hjust = 1, size = 12,face = "bold"),
    axis.text.y = element_text(size = 11),
    legend.title = element_text(face = "bold"),
    legend.position = "right",
    strip.text = element_text(face = "bold", size = 0),
    panel.spacing = unit(.1, "lines"),
    panel.grid.major.x = element_blank()
  ) +
  guides(fill = guide_legend(override.aes = list(size = 4)))
dev.off()


df.brain$Organ <- "Brain"
df.heart$Organ <- "Heart"
df.heart$Proportion <- -df.heart$Proportion
df.merged <- rbind(df.brain, df.heart)

df.merged <- subset(df.merged,Age.GW%Nin%c("GW11","GW15"))

pdf("../Results/Manuscript/RNA.proportions(version2).pdf",width = 12,height = 3.5)
ggplot(df.merged, aes(x = Age.GW, y = Proportion, fill = Cellsubtype)) +
  geom_bar(stat = "identity", color = "white", size = 0.3) +
  scale_fill_manual(values = all_colors) +
  coord_flip() +
  labs(
    title = "Cell Subtype Proportions: Heart (Left) vs. Brain (Right)",
    x = "Gestational Week",
    y = "Proportion",
    fill = "Cell Subtype"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(face = "bold", size = 16, hjust = 0.5),
    axis.text.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(size = 10),
    legend.title = element_text(face = "bold"),
    legend.position = "right",
    strip.text = element_text(face = "bold", size = 12),
    panel.spacing = unit(1, "lines"),
    panel.grid.major.x = element_blank()
  ) +
  geom_hline(yintercept = 0, color = "black")
dev.off()

```

```{r Dims2,fig.width=25,fig.height=10}

###########################################
#    Differential gene expression analysis     
###########################################


# RNA.int <- SplitObject(RNA.int,split.by = "Organ")
# 
# RNA.int$Brain <- SCTransform(RNA.int$Brain,assay = "RNA")
# RNA.int$Heart <- SCTransform(RNA.int$Heart,assay = "RNA")
# 
# saveRDS(RNA.int,"../Rsave/RNA.int.SPLIT.Rds")
RNA.int <- readRDS("../Rsave/RNA.int.SPLIT.Rds")
RNA.int$Brain <- SetIdent(RNA.int$Brain,value = RNA.int$Brain$newL3_Cell_type)
RNA.int$Heart <- SetIdent(RNA.int$Heart,value = RNA.int$Heart$newL3_Cell_type)


# 
# RNA.int.heart.degs <- FindAllMarkers(RNA.int$Heart,logfc.threshold = 0.5,densify = T,test.use = "MAST",assay = "RNA")
# RNA.int.brain.degs <- FindAllMarkers(RNA.int$Brain,logfc.threshold = 0.5,densify = T,test.use = "MAST",assay = "RNA")
# RNA.int.heart.degs.SCT <- FindAllMarkers(RNA.int$Heart,logfc.threshold = 0.5,densify = T,test.use = "MAST",assay = "SCT")
# RNA.int.brain.degs.SCT <- FindAllMarkers(RNA.int$Brain,logfc.threshold = 0.5,densify = T,test.use = "MAST",assay = "SCT")
# 
# 
# save(RNA.int.heart.degs,RNA.int.brain.degs,RNA.int.heart.degs.SCT,RNA.int.brain.degs.SCT,file = "../Rsave/RNA.int.organ.degs.Rdata")

load("../Rsave/RNA.int.organ.degs.Rdata")


RNA.int.brain.degs$cluster2 <- gsub("Brain_","",RNA.int.brain.degs$cluster)
RNA.int.brain.degs$cluster2 <- factor(RNA.int.brain.degs$cluster2, levels = levels(RNA.int$Brain$newL3_Cell_type))
RNA.int.brain.degs <- RNA.int.brain.degs[order(RNA.int.brain.degs$cluster2),]

RNA.int.heart.degs$cluster2 <- gsub("Heart_","",RNA.int.heart.degs$cluster)
RNA.int.heart.degs$cluster2 <- factor(RNA.int.heart.degs$cluster2, levels = levels(RNA.int$Heart$newL3_Cell_type))
RNA.int.heart.degs <- RNA.int.heart.degs[order(RNA.int.heart.degs$cluster2),]


top5.Brain <- c()
for (clusters in unique(RNA.int.brain.degs$cluster)) {
  x <- subset(RNA.int.brain.degs, cluster == clusters )
  x <- x[order(-x$avg_log2FC, -x$p_val_adj),][1:5,]
  top5.Brain <- rbind(top5.Brain,x)
}

top5.Heart <- c()
for (clusters in unique(RNA.int.heart.degs$cluster)) {
  x <- subset(RNA.int.heart.degs, cluster == clusters )
  x <- x[order(-x$avg_log2FC, -x$p_val_adj),][1:5,]
  top5.Heart <- rbind(top5.Heart,x)
}

top5.Brain.sct <- c()
for (clusters in unique(RNA.int.brain.degs.SCT$cluster)) {
  x <- subset(RNA.int.brain.degs.SCT, cluster == clusters )
  x <- x[order(-x$avg_log2FC, -x$p_val_adj),][1:5,]
  top5.Brain.sct <- rbind(top5.Brain.sct,x)
}

top5.Heart.sct <- c()
for (clusters in unique(RNA.int.heart.degs.SCT$cluster)) {
  x <- subset(RNA.int.heart.degs.SCT, cluster == clusters )
  x <- x[order(-x$avg_log2FC, -x$p_val_adj),][1:5,]
  top5.Heart.sct <- rbind(top5.Heart.sct,x)
}



DotPlot(RNA.int$Brain,group.by = "newL3_Cell_type",features = unique(top5.Brain.sct$gene),assay = "SCT")+scale_color_gradient2(low = "grey60",mid = "white",high = organ_colors[1])+theme_bw()+theme(axis.text = element_text(face = "bold",size = 20),title = element_text(face = "bold",size = 20))+rotate_x_text(90)+ggtitle("Brain")

DotPlot(RNA.int$Brain,group.by = "newL3_Cell_type",features = unique(top5.Brain$gene),assay = "RNA")+scale_color_gradient2(low = "grey60",mid = "white",high = organ_colors[1])+theme_bw()+theme(axis.text = element_text(face = "bold",size = 20),title = element_text(face = "bold",size = 20))+rotate_x_text(90)+ggtitle("Brain")

DotPlot(RNA.int$Heart,group.by = "newL3_Cell_type",features = unique(top5.Heart.sct$gene),assay = "SCT")+scale_color_gradient2(low = "grey60",mid = "white",high = organ_colors[2])+theme_bw()+theme(axis.text = element_text(face = "bold",size = 20),title = element_text(face = "bold",size = 20))+rotate_x_text(90)+ggtitle("Heart")

DotPlot(RNA.int$Heart,group.by = "newL3_Cell_type",features = unique(top5.Heart$gene),assay = "RNA")+scale_color_gradient2(low = "grey60",mid = "white",high = organ_colors[2])+theme_bw()+theme(axis.text = element_text(face = "bold",size = 20),title = element_text(face = "bold",size = 20))+rotate_x_text(90)+ggtitle("Heart")


```


```{r Dims2,fig.width=8,fig.height=10}

###########################################
#   Hirachical clustering 
###########################################

DotPlot(RNA.int,group.by = "newL3_Cell_type",features = unique(c(top5.Brain.sct$gene,top5.Heart.sct$gene)),assay = "RNA")+scale_color_gradient2(low = "grey60",mid = "white",high = organ_colors[1])+theme_bw()+theme(axis.text = element_text(face = "bold",size = 20),title = element_text(face = "bold",size = 20))+rotate_x_text(90)+ggtitle("Brain")


library(ggdendro)


# Set the identity to Organ_L3_Cell_type
Idents(RNA.int) <- "Organ_L3_Cell_type"


# RNA.int.ALL.DEGS <- FindAllMarkers(RNA.int,only.pos = T,logfc.threshold = 0.7,densify = T,assay = "RNA")
# RNA.int.ALL.DEGS <- subset(RNA.int.ALL.DEGS,p_val_adj<0.01)
# saveRDS(RNA.int.ALL.DEGS,"../RNA.int.ALL.DEGS.Rds")

RNA.int.ALL.DEGS <- readRDS("../RNA.int.ALL.DEGS.Rds")

top.all <- c()
for (clusters in unique(RNA.int.ALL.DEGS$cluster)) {
  x <- subset(RNA.int.ALL.DEGS, cluster == clusters )
  x <- x[order(-x$avg_log2FC, -x$p_val_adj),][1:100,]
  top.all <- rbind(top.all,x)
}

# Use top genes for clustering
avg_exp <- AverageExpression(RNA.int, features = unique(top.all$gene), return.seurat = FALSE)$RNA
scaled_exp <- t(scale(t(avg_exp)))

# Hierarchical clustering
hc <- hclust(dist(t(scaled_exp)))  # Cluster columns
cluster_order <- hc$labels[hc$order]  # Use this order!



library(ggdendro)

dend_data <- dendro_data(as.dendrogram(hc), type = "rectangle")

# Adjust dend_plot
dend_plot <- ggplot() +
  geom_segment(data = segment(dend_data),
               aes(x = x, y = y, xend = xend, yend = yend)) +
  scale_x_continuous(breaks = 1:length(cluster_order),
                     labels = cluster_order) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, size = 10),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = margin(0, 20, 10, 20)  # Add enough bottom margin
  )


RNA.int$Organ_L3_Cell_type <- factor(RNA.int$Organ_L3_Cell_type, levels = cluster_order)

top.3 <- RNA.int.ALL.DEGS %>%
  group_by(cluster) %>%
  arrange(desc(avg_log2FC)) %>%
  slice_head(n = 2)
top.3$cluster <- factor(top.3$cluster, levels = cluster_order)
top.3 <- top.3[order(top.3$cluster),]



dotplot <- DotPlot(RNA.int,
                   features = unique(top.3$gene),
                   group.by = "Organ_L3_Cell_type",
                   assay = "RNA") +
  coord_flip() +
  scale_color_gradient2(low = "grey80", mid = "white", high = "steelblue") +
  theme_bw() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(face = "italic", size = 10),
    axis.ticks.x = element_blank(),
    legend.position = "none",
    strip.text = element_text(face = "bold", size = 12),
    axis.title = element_blank(),
    plot.margin = margin(0, 10, 0, 10)
  ) +
  ggtitle("")
library(patchwork)

# Wrap both into fixed-grobs so layout is fully aligned
final_plot <- wrap_elements(dend_plot) / wrap_elements(dotplot) +
  plot_layout(heights = c(2, 5), guides = "collect")

```



```{r Dims2,fig.width=15,fig.height=10}

scRNA <- readRDS("./OMIX008302-02.edited.rds")

scRNA$L1_Cell_type[scRNA$L3_Cell_type=="Debri"] <- "Debri"
scRNA$L1_Cell_type[scRNA$L3_Cell_type=="Doublet"] <- "Doublet"
celltype_colors <- c(
  "NPCs"        = "#1f78b4",  # blue
  "Neurons"     = "#33a02c",  # green
  "Vasculature" = "#e31a1c",  # red
  "Immune"      = "#ff7f00",  # orange
  "HSCs"        = "#6a3d9a",  # purple
  "Debri"       = "#b15928",  # brown
  "CMs"         = "#a6cee3",   # light blue
  "Doublet"     = "grey")


scRNA$L1_Cell_type <- factor(scRNA$L1_Cell_type,levels = c("Vasculature","NPCs", "Neurons",   "Immune" , "HSCs" , "CMs","Debri","Doublet"))


axis <- ggh4x::guide_axis_truncated(
  trunc_lower = unit(0, "npc"),
  trunc_upper = unit(1.5, "cm"))

p1 <- DimPlot(scRNA,group.by = "L1_Cell_type",label = F,repel = T,cols = celltype_colors,raster = T,pt.size = 0.5)+ggtitle("Cell types")+
 guides(x = axis, y = axis) +xlab("UMAP 1")+ylab("UMAP 2")+
  theme(axis.line = element_line(arrow = arrow(angle = 20, length = unit(4, "points"))),
        axis.title = element_text(hjust = 0,size = 10),axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank())

pdf("../Results/Manuscript/Figure1/Supplementary1.pdf",height = 3,width = 4)
p1
dev.off()

"%Nin%" <- Negate("%in%")
scRNA <- subset(scRNA,L1_Cell_type %Nin% c("Debri","Doublet"))
scRNA <- RunUMAP(scRNA,reduction = "harmony",dims = 1:20)

organ_colors <- c(
  "Brain" = "#00bfc4",  # vibrant teal (cool, crystalline)
  "Heart" = "#f56476"   # coral rose (warm, emotional)
)

age_colors <- c(
  "GW06" = "#d73027",  # deep red
  "GW07" = "#f46d43",
  "GW08" = "#fdae61",
  "GW09" = "#fee08b",
  "GW10" = "#e0f3f8",
  "GW11" = "#abd9e9",
  "GW12" = "#74add1",
  "GW14" = "#4575b4",
  "GW15" = "#313695",
  "GW24" = "#2c104d"   # deep blue-violet
)

celltype_colors <- c(
  "NPCs"        = "#1f78b4",  # blue
  "Neurons"     = "#33a02c",  # green
  "Vasculature" = "#e31a1c",  # red
  "Immune"      = "#ff7f00",  # orange
  "HSCs"        = "#6a3d9a",  # purple
  "CMs"         = "#a6cee3"   # light blue
)


axis <- ggh4x::guide_axis_truncated(
  trunc_lower = unit(0, "npc"),
  trunc_upper = unit(1.5, "cm"))

p1 <- DimPlot(scRNA,group.by = "Organ",label = F,repel = T,cols = organ_colors,raster = T,pt.size = 0.5)+ggtitle("Organs")+
 guides(x = axis, y = axis) +xlab("UMAP 1")+ylab("UMAP 2")+
  theme(axis.line = element_line(arrow = arrow(angle = 20, length = unit(4, "points"))),
        axis.title = element_text(hjust = 0,size = 10),axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank())


axis <- ggh4x::guide_axis_truncated(
  trunc_lower = unit(0, "npc"),
  trunc_upper = unit(0, "cm"))

p2 <- DimPlot(scRNA,group.by = "Age",label = F,repel = T,cols = age_colors,raster = T,pt.size = 0.5)+ggtitle("Timepoints")+
 guides(x = axis, y = axis) +xlab("")+ylab("")+
  theme(axis.line = element_line(arrow = arrow(angle = 20, length = unit(0, "points"))),
        axis.title = element_text(hjust = 0,size = 10),axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank())


scRNA$L1_Cell_type <- factor(scRNA$L1_Cell_type,levels = c("Vasculature","NPCs", "Neurons",   "Immune" , "HSCs" , "CMs"))


p3 <- DimPlot(scRNA,group.by = "L1_Cell_type",label = F,repel = T,cols = celltype_colors,raster = T,pt.size = 0.5)+ggtitle("Cell types")+
 guides(x = axis, y = axis) +xlab("")+ylab("")+
  theme(axis.line = element_line(arrow = arrow(angle = 20, length = unit(0, "points"))),
        axis.title = element_text(hjust = 0,size = 10),axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank())


pdf("../Results/Manuscript/Figure1/Dims.pdf",height = 3,width = 12)
p1+p2+p3
dev.off()



```



```{r Dims2,fig.width=15,fig.height=10}
scRNA <- SetIdent(scRNA,value = "L1_Cell_type")

# degs.L1 <- FindAllMarkers(scRNA,only.pos = T,logfc.threshold = 0.5,densify = T)
# saveRDS(degs.L1,"./degs.L1.Dberi.Doublets.removed.Rds")

degs.L1 <- readRDS("./degs.L1.Dberi.Doublets.removed.Rds")
degs.L1 <- subset(degs.L1,p_val_adj<0.05)


top10 <- c()
for (clusters in unique(degs.L1$cluster)) {
  x <- subset(degs.L1, cluster == clusters )
  x <- x[order(-x$avg_log2FC, -x$p_val_adj),][1:10,]
  top10 <- rbind(top10,x)
}


DotPlot(scRNA,
                 #selecting top30 genes for the dotplot
                 features = unique(top10$gene)
,assay = "RNA",scale.by = "size")+ggtitle("Cell type Top10 DEGs")+theme_bw()+coord_flip()+rotate_x_text(90)+scale_color_gradient2(low = "navyblue",mid = "white",high = "red")+theme(axis.text = element_text(face = "bold"))


pdf("../Results/Manuscript/Figure1/Supplementary2.pdf",height = 15,width = 4.5)
 DotPlot(scRNA,
                 #selecting top30 genes for the dotplot
                 features = unique(top10$gene)
,assay = "RNA",scale.by = "size")+ggtitle("Cell type Top10 DEGs")+theme_bw()+coord_flip()+rotate_x_text(90)+scale_color_gradient2(low = "navyblue",mid = "white",high = "red")+theme(axis.text = element_text(face = "bold"))
dev.off()



canonical_markers <- list(
  Vasculature = c("SPARCL1","CAV1","COL3A1"),
  NPCs = c("SOX2", "HES5", "TTYH1"),
  Neurons = c("TUBB3", "STMN2", "MAP2"),
  Immune = c("IL1B", "CCL3", "CXCL8"),
  HSCs = c("AHSP", "ALAS2", "GYPC"),
  CMs = c("TNNT2", "ACTC1", "TPM1")
)


DotPlot(scRNA,
                 #selecting top30 genes for the dotplot
                 features = unique(unlist(canonical_markers))
,assay = "RNA",scale.by = "size")+ggtitle("Cell type markers")+theme_bw()+coord_flip()+rotate_x_text(90)+scale_color_gradient2(low = "navyblue",mid = "white",high = "red")+theme(axis.text = element_text(face = "bold"))


pdf("../Results/Manuscript/Figure1/Dotplot.Celltypes.pdf",height = 5.5,width = 4)
 DotPlot(scRNA,
                 #selecting top30 genes for the dotplot
                 features = unique(unlist(canonical_markers))
,assay = "RNA",scale.by = "size")+ggtitle("Cell type markers")+theme_bw()+coord_flip()+rotate_x_text(90)+scale_color_gradient2(low = "navyblue",mid = "white",high = "red")+theme(axis.text = element_text(face = "bold"))
dev.off()


saveRDS(scRNA,"../Rsave/OMIX008302-02_Debri.Douplets.removed.rds")

```


# Chromatin+RNA

```{r Multi1,fig.width=15,fig.height=10}
rm(scRNA)
gc()
# Changing the Seurat version to 5

.libPaths("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Rloading/4.4.Spatial/")
# install.packages('Seurat')
unloadNamespace("Seurat")  
library(Seurat)

.libPaths("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Rloading/4.4")

Multi.harmony <- readRDS("../Rsave/OMIX008302-03.rds")
Multi.harmony <- UpdateSeuratObject(Multi.harmony)

Multi.harmony$Common.Annot.L1 <- Multi.harmony$L1_Cell_type
Multi.harmony$Common.Annot.L1[Multi.harmony$Experiment=="scATAC"] <- subset(Multi.harmony,Experiment=="scATAC")$predicted.Cell_type
Multi.harmony$Common.Annot.L1[grep("ECs",Multi.harmony$Common.Annot.L1)] <- "ECs"
Multi.harmony$Common.Annot.L1[grep("Mural",Multi.harmony$Common.Annot.L1)] <- "Mural"
pattern <- paste(c("Tip cells", "Sinus Venosus","Mural_SMCs","Mural_Precursors","Mural_Fibroblasts", "Mural_Mitotic", "Mural_Pericytes","Endocardial-like","Mural","ECs"), collapse = "|")
Multi.harmony$Common.Annot.L1[grep(pattern,Multi.harmony$Common.Annot.L1)] <- "Vasculature"

Multi.harmony$Organ.all <- Multi.harmony$Organ
Multi.harmony$Organ.all[grep("B_",Multi.harmony$orig.ident)] <- "Brain"
Multi.harmony$Organ.all[grep("H_",Multi.harmony$orig.ident)] <- "Heart"

Multi.harmony$Experiment <- gsub("scATAC","scATACseq",Multi.harmony$Experiment)
Multi.harmony$Experiment <- gsub("scRNA","scRNAseq",Multi.harmony$Experiment)

DefaultAssay(Multi.harmony) <- "ATAC"

pdf("../Results/Manuscript/Figure1/Multi.L1.Cell_type.dim.pdf",height = 4,width = 7)

DimPlot(Multi.harmony,group.by = "Common.Annot.L1",label = F,repel = T,cols = celltype_colors,raster = T,pt.size = 0.5,split.by = "Experiment")+ggtitle("Cell types")+
 guides(x = axis, y = axis) +xlab("")+ylab("")+
  theme(axis.line = element_line(arrow = arrow(angle = 20, length = unit(0, "points"))),
        axis.title = element_text(hjust = 0,size = 10),axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank())
dev.off()



library(ggplot2)
library(dplyr)

# Create 3-way table
tab <- table(Multi.harmony$Common.Annot.L1, Multi.harmony$Organ.all, Multi.harmony$Experiment)

# Convert to data frame
df <- as.data.frame(tab)
colnames(df) <- c("Celltype", "Organ", "Experiment", "Count")

# Compute proportions within each Celltype * Experiment group
df <- df %>%
  group_by(Celltype, Experiment) %>%
  mutate(Proportion = Count / sum(Count))

# Plot with facets for experiments

library(ggthemes)
library(viridis)



pdf("../Results/Manuscript/Figure1/Proportions1.Cell_type.pdf",height = 4,width = 7)

# Improved version
ggplot(df, aes(x = Celltype, y = Proportion, fill = Organ)) +
  geom_bar(stat = "identity", width = 0.85, color = "white", size = 0.2) +
  facet_wrap(~ Experiment, scales = "free_x") +
  scale_fill_viridis_d(option = "C", begin = 0.2, end = 0.9) +
  labs(
    title = "Distribution of Organs Across Cell Types",
    subtitle = "",
    x = NULL,
    y = "Proportion",
    fill = "Organ"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 12, color = "gray30"),
    axis.text.x = element_text(angle = 40, hjust = 1, size = 10),
    axis.text.y = element_text(size = 11),
    legend.title = element_text(face = "bold"),
    legend.position = "right",
    strip.text = element_text(face = "bold", size = 12),
    panel.spacing = unit(1.5, "lines"),
    panel.grid.major.x = element_blank()
  ) +
  guides(fill = guide_legend(override.aes = list(size = 4)))
dev.off()


```

```{r Neural.markers,fig.width=20,fig.height=5}
library(Signac)
library(GenomicRanges)

# Read the CSV file
peaks_df <- read.csv("../Data/AmeenM.2022/GSE181346_processed_data/peaks_allCells_bpnet.csv", header = TRUE,sep = "\t")

# Keep only the first 3 columns
peaks_clean <- peaks_df[, 1:3]
colnames(peaks_clean) <- c("chr", "start", "end")

# Convert to GRanges
peaks_gr <- makeGRangesFromDataFrame(peaks_clean, seqnames.field = "chr", start.field = "start", end.field = "end")

# Optional: Remove duplicate or overlapping ranges
peaks_gr <- reduce(peaks_gr)
library(Signac)

# Create the fragment object
frags <- CreateFragmentObject(
  path = "../Data/AmeenM.2022/Raw/102/GSM5495102_F6_v2_fragments.tsv.gz"
)

# Generate the peak-cell count matrix
peak_matrix <- FeatureMatrix(
  fragments = frags,
  features = peaks_gr,
  cells = NULL  # or provide cell barcodes if available
)

# Create ChromatinAssay
chrom_assay <- CreateChromatinAssay(
  counts = peak_matrix,
  fragments = "GSM5495102_F6_v2_fragments.tsv.gz",
  genome = 'hg38'
)

# Create Seurat object
seurat_atac <- CreateSeuratObject(
  counts = chrom_assay,
  assay = "peaks"
)

```



