---
title: "SpatialTranscriptomics"
output: html_document
date: "2026-03-02"
---

A report by **Elyas.Mohammadi**

```{r libraries}

# Changing the Seurat version to 5
.libPaths("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Rloading/4.4.Spatial/")
library(scales)
library(ggplot2)

# install.packages('Seurat')
#unloadNamespace("Seurat")  
library(Seurat)
.libPaths("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Rloading/4.4")

# library(data.table)
library(harmony)


library(ggrepel)
library(ggpubr)
library(patchwork)
# library(clusterProfiler)
# library(org.Hs.eg.db)
library(AnnotationHub)
# library(EnsDb.Hsapiens.v86)
library(ggthemes)
library(viridis)
library(dplyr)
library(GenomicRanges)
library(GenomeInfoDb)
library(tidyr)
library(RColorBrewer)
library(scales)
library(gridExtra)
library(pheatmap)

library(ggh4x)
axis <- ggh4x::guide_axis_truncated(
  trunc_lower = unit(0, "npc"),
  trunc_upper = unit(1.5, "cm"))

library(Signac)


```



```{r load-hdf5r}

proj_lib <- "/cfs/klemming/projects/supr/naiss2023-6-180/Theo/seuratdisk_build/Rlib"
h5_root  <- "/cfs/klemming/projects/supr/naiss2023-6-180/Theo/rlinger_build/opt/hdf5-1.12.2"
h5_lib   <- file.path(h5_root, "lib")

.libPaths(c(proj_lib, .libPaths()))

Sys.setenv(
  LD_LIBRARY_PATH = paste(h5_lib, Sys.getenv("LD_LIBRARY_PATH"), sep=":"),
  HDF5_DIR  = h5_root,
  HDF5_ROOT = h5_root
)

mklink <- function(target_glob, link_name) {
  link_path <- file.path(h5_lib, link_name)
  if (!file.exists(link_path)) {
    cand <- Sys.glob(file.path(h5_lib, target_glob))
    if (length(cand)) {
      message("Linking ", basename(cand[1]), " -> ", link_name)
      system2("ln", c("-sfn", cand[1], link_path))
    } else {
      message("No match for ", target_glob, " in ", h5_lib)
    }
  }
}

mklink("libhdf5.so.200*",     "libhdf5.so.200")
mklink("libhdf5_hl.so.200*",  "libhdf5_hl.so.200")
mklink("libhdf5_cpp.so.200*", "libhdf5_cpp.so.200")  # present on some builds

suppressWarnings({
  try(dyn.load(file.path(h5_lib, "libhdf5.so.200")),    silent = TRUE)
  try(dyn.load(file.path(h5_lib, "libhdf5_hl.so.200")), silent = TRUE)
  # cpp is optional; ignore if missing
  if (file.exists(file.path(h5_lib, "libhdf5_cpp.so.200")))
    try(dyn.load(file.path(h5_lib, "libhdf5_cpp.so.200")), silent = TRUE)
})


suppressPackageStartupMessages({
  library(hdf5r,      lib.loc = proj_lib)
  library(SeuratDisk, lib.loc = proj_lib)
})



########################################
#Rlinger Rcpp loader: loads the packages and links the dependencies 

gc()
proj_lib <- "/cfs/klemming/projects/supr/naiss2023-6-180/Theo/rlinger_build/Rlib"
h5_root  <- "/cfs/klemming/projects/supr/naiss2023-6-180/Theo/rlinger_build/opt/hdf5-1.12.2"
h5_lib   <- file.path(h5_root, "lib")

.libPaths(c(proj_lib, .libPaths()))
Sys.setenv(
  LD_LIBRARY_PATH = paste(h5_lib, Sys.getenv("LD_LIBRARY_PATH"), sep=":"),
  HDF5_DIR  = h5_root,
  HDF5_ROOT = h5_root
)
suppressWarnings({
  try(dyn.load(file.path(h5_lib, "libhdf5.so.200")),     silent = TRUE)
  try(dyn.load(file.path(h5_lib, "libhdf5_hl.so.200")),  silent = TRUE)
  try(dyn.load(file.path(h5_lib, "libhdf5_cpp.so.200")), silent = TRUE)
})

suppressPackageStartupMessages({
  library(RcppPlanc, lib.loc = proj_lib)
  library(rliger,     lib.loc = proj_lib)
  library(Seurat)
})

library(rliger)
library(dplyr)
library(cowplot)

```


```{r ECs_Arterial,fig.width=18,fig.height=5}

############ ############ ############ ############ 
############     Loding the data       ############ 
############ ############ ############ ############ 

path="/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Projects/Tiantan/Rsave/Atlas.organs/WholeEmbryoVisium"

dirs <- list.dirs(path,recursive = F)

st.obj <- list()
for (dir in 1:length(dirs)) {
 st.obj[[dir]] <- Load10X_Spatial(dirs[dir],assay = "Spatial",slice = basename(dirs[dir]))
 st.obj[[dir]]$orig.ident <-  basename(dirs[dir])
 # st.obj[[dir]] <- NormalizeData(st.obj[[dir]])
}

st.obj <- Reduce(merge,st.obj)

meta <- read.csv("/cfs/klemming/projects/supr/naiss2023-6-180/elyasmo/Projects/Tiantan/Rsave/Atlas.organs/sample_metadata_20240308.csv",sep = ";")

st.obj@meta.data[,4:7] <- meta[match(st.obj$orig.ident,meta$slide_id),]


# VlnPlot(st.obj,features = c("nCount_Spatial","nFeature_Spatial"),split.by = "orig.ident" ,ncol = 4)
st.obj <- subset(
  st.obj,
  subset = nCount_Spatial  > 0 &
           nFeature_Spatial > 100 &
           (if ("in_tissue" %in% colnames(st.obj@meta.data)) in_tissue == 1 else TRUE)
)


gene_list <- c(
"HMGA2","HIST1H2BO","HIST1H1B","HIST2H2AB","HIST1H2AD",
"SIX1","SIX2","EYA1","FOXF2","TBX18","FOXC1","ZIC1","GPC4",
"SOX2","SOX3","HES5","RFX4","POU3F2","PTPRZ1","WNT7A","TTYH1",
"APOA4","RBP4","APOB","FGA","APOC2","APOC3","FETUB","HPX",
"MYH7","MYL2","MYL3","TNNC1","NPPA","MYBPC3","ACTN2","CKM",
"DCX","NEFL","ELAVL4","L1CAM","GAP43","STMN4","CNTN2","SCG2",
"TBX4","PITX1","SMOC2","EGFL6","COL15A1","CEBPD","MME",
"MYF5","MYOG","MYH3","MYLPF","TTN","TNNC2","PAX3","SIX1",
"SOX10","PRPH","NTRK1","MPZ","NEUROD1","PRDM12","SHOX2","S100B",
"WT1","GATA6","ZFPM2","TBX5","PRDM6","COLEC11","GATA5","RELN",
"OTX2","SIX3","RAX","EMX2","FEZF2","ARX","LHX2","NR2E1",
"KLF1","GATA1","HEMGN","ALAS2","SLC4A1","SPTA1","SPTB","AHSP",
"CYP3A7","ALDOB","SLC2A2","SERPINA1","A1BG","OTC","PAH","CFB",
"KRT7","CLDN6","GRHL2","TACSTD2","ITGB4","THBD","WNT6","ANXA3",
"EPCAM","CLDN3","CLDN4","ST14","PRSS22","WFDC2","FOXE1","OVOL2","KLF5",
"HOXA6","NKX2-3","HAND1","MAB21L2","TSHZ2","EDN3","PDE3A",
"DLX1","DLX2","DLX5","DLX6","HAND2","ALX1","BARX1","RSPO2","PRRX1",
"SPARC","KRT8","DCN","COL3A1","PITX2","HBE1","GSTP1",
"NPHS1","NPHS2","PAX2","HNF1B","OSR2","PLAC1","KCNJ15","ENPEP",
"SHH","FOXA2","NKX6-1","NKX6-2","ARX","RFX4","SLIT1","SPON1","DNAH7","RSPH4A","CFAP47",
"FOXP2","COLEC12","GJA1","HPSE2","CCN1","HIST1H2AB","HIST1H3D","HIST1H4I",
"TCF21","CXCL12","DLK1","GPC3","APOB","APOA1","AFP","FABP1"
)



```



```{r ECs_Arterial,fig.width=18,fig.height=5}

############ ############ ############ ############ 
############      CCA        ############ 
############ ############ ############ ############ 
# 1) Split into a list by tissue section
obj.list <- SplitObject(st.obj, split.by = "orig.ident")

# 2) SCTransform each section separately


obj.list <- lapply(obj.list, function(x) {
  DefaultAssay(x) <- "Spatial"
  x <- SCTransform(
    x,assay = DefaultAssay(x),
    return.only.var.genes = FALSE,  # <- ensures feature stability
    verbose = FALSE
  )
})

# 3) Select integration features
features <- SelectIntegrationFeatures(
  object.list = obj.list,
  nfeatures   = 3000
)

# 4) Prep SCT integration
obj.list <- PrepSCTIntegration(
  object.list     = obj.list,
  anchor.features = features
)

# 5) Find anchors
anchors <- FindIntegrationAnchors(
  object.list         = obj.list,
  normalization.method = "SCT",
  anchor.features      = features
)


# 6) Integrate the data
st.integrated <- IntegrateData(
  anchorset           = anchors,
  normalization.method = "SCT"
)

# 7) Downstream
DefaultAssay(st.integrated) <- "integrated"

saveRDS(st.integrated,"../Rsave/st.obj2.Rds")


st.integrated <- RunPCA(st.integrated,npcs = 50)
st.integrated <- RunUMAP(st.integrated,dims = 1:30)


st.integrated <- st.integrated %>%
    FindNeighbors(reduction = "pca", dims = 1:30) %>%
    FindClusters(resolution = c(0.1,0.2,0.3,0.4,0.6,0.7,0.5,0.8,1,1.5))

colnames(st.obj@meta.data)[10:20] <- gsub("integrated","integrated.sct",colnames(st.obj@meta.data)[10:20])


############ ############ ############ ############ 
############      rliger- iNMF         ############ 
############ ############ ############ ############ 

st.obj <- st.integrated
DefaultAssay(st.obj) <- "Spatial"

st.obj <- st.obj %>%
  normalize() %>%
  selectGenes() %>%
  scaleNotCenter()

st.obj <- st.obj %>%
    runINMF(k = 20,datasetVar = "orig.ident",nIteration = 40,lambda = 5) %>%
    quantileNorm(datasetVar = "orig.ident")

st.obj <- RunUMAP(st.obj, reduction = "inmfNorm", dims = 1:20)

DimPlot(st.obj, group.by = "orig.ident")

st.obj <- st.obj %>%
    FindNeighbors(reduction = "inmfNorm", dims = 1:20) %>%
    FindClusters(resolution = c(.1,.2,0.3,0.5,0.8,1))

colnames(st.obj@meta.data)[22:27] <- gsub("Spatial","liger",colnames(st.obj@meta.data)[22:27])

SpatialDimPlot(st.obj,images = Images(st.obj)[3],group.by = "liger_snn_res.0.5",pt.size.factor = 3)
SpatialDimPlot(st.obj,images = Images(st.obj)[3],group.by = "inmfNorm.cluster",pt.size.factor = 3)




############ ############ ############ ############ 
############      Harmony        ############ 
############ ############ ############ ############ 

st.obj <- readRDS("../Rsave/st.obj2.Rds")

st.obj <- PrepSCTFindMarkers(st.obj, assay = "SCT")
DefaultAssay(st.obj) <- "integrated"

# st.obj <- FindVariableFeatures(st.obj)
# st.obj <- ScaleData(st.obj)
st.obj <- RunHarmony(st.obj,
  group.by.vars=c("orig.ident","cs_stage"),
  reduction.use = "pca",
  dims.use = 1:50,
  verbose = TRUE,
  reduction.save = "harmony",
  project.dim = TRUE,max_iter = 30)

st.obj <- RunUMAP(st.obj, reduction = "harmony", dims = 1:30,reduction.name = "umap_harmony")

st.obj <- st.obj %>%
    FindNeighbors(reduction = "harmony", dims = 1:30) %>%
    FindClusters(resolution = c(0.1,0.2,0.3,0.5,0.8,1,1.5))

colnames(st.obj@meta.data)[28:34] <- gsub("integrated","integrated.har",colnames(st.obj@meta.data)[28:34])


p1 <- SpatialDimPlot(st.obj,images = Images(st.obj)[2],group.by = "integrated.sct_snn_res.0.2",pt.size.factor = 3)+ggtitle("integrated.sct_snn_res.0.2")
p2 <- SpatialDimPlot(st.obj,images = Images(st.obj)[2],group.by = "inmfNorm.cluster",pt.size.factor = 3)+ggtitle("inmfNorm.cluster")
p3 <- SpatialDimPlot(st.obj,images = Images(st.obj)[2],group.by = "liger_snn_res.0.2",pt.size.factor = 3)+ggtitle("liger_snn_res.0.2")
p4 <- SpatialDimPlot(st.obj,images = Images(st.obj)[2],group.by = "integrated.har_snn_res.0.2",pt.size.factor = 3)+ggtitle("integrated.har_snn_res.0.2")

(p1+p2)/(p3+p4)

saveRDS(st.obj,"../Rsave/st.obj2.Rds")


```





```{r,fig.width=50,fig.height=30}


library(patchwork)

SpatialFeaturePlotBlend <- function(object, features, combine = TRUE,
                                    feature_1_alt_name = NULL,
                                    feature_2_alt_name = NULL, assay = NULL,
                                    bottom_left = "grey30",
                                    bottom_right = "#FF0000",
                                    top_left = "#00FF00",
                                    top_right = "#FFFF00",
                                    use_seurat_backend = FALSE,
                                    fp_extra_arguments = list(),
                                    sfp_extra_arguments = list(),
                                    pt.size.factor=3,
                                    # images=images,
                                    image.alpha = 0.1,
                                    stroke = 0.1)  {
    
    # Generate a grid of RGB color values given the requested corner colours.
    gen_color_grid <- function(side_length, bottom_left, bottom_right,
                               top_left, top_right) {
        
        grad_gen <- function(start, end, n = side_length) {
            colfunc <- colorRampPalette(c(start, end))
            return(colfunc(n))
        }
        
        # x_y = "x to y"; "bl" = "bottom left", etc
        bl_tl <- grad_gen(bottom_left, bottom_right)
        br_tr <- grad_gen(top_left, top_right)
        
        l <- lapply(seq_len(length(bl_tl)),
                    function(i) {
                        start <- bl_tl[i]
                        end <- br_tr[i]
                        new_grad <- grad_gen(start, end)
                    })
        
        return(t(matrix(unlist(l), ncol = side_length, nrow = side_length)))
    }
    
    custom_color_SpatialDimPlot <- function(cells_obj, image_name,
                                            new_md_column_name,
                                            colors_per_spot, ...) {
        cells_obj[[new_md_column_name]] <- colors_per_spot
        names(colors_per_spot) <- as.character(colors_per_spot)
        
        p <- SpatialDimPlot(cells_obj, new_md_column_name,pt.size.factor=pt.size.factor, 
                                                   image.alpha = image.alpha,stroke = stroke,
                            cols = colors_per_spot, images = image_name, ...) +
            ggtitle(new_md_column_name) +
            blend_plot_theme
        return(p)
    }
    
    extract_colors_from_ggplot <- function(p) {
        built <- ggplot_build(p)$data[[1]]
        if (!is.na(built[1, "fill"])) {
            col_to_use <- "fill"
        } else {
            col_to_use <- "colour"
        }
        return(built[, col_to_use])
    }
    
    if (length(features) != 2) {
        stop(paste(c("Incorrect number of features. ",
                     "Requires two features, received ",
                     length(features))))
    }
    
    if (!is.null(assay)) {
        DefaultAssay(object) <- assay
    }
    
    if (length(fp_extra_arguments) > 0) {
        use_seurat_backend <- TRUE
    }
    
    blend_plot_theme <- theme(legend.position = "none",
                              plot.title = element_text(hjust = 0.5))
    
    plot_list_outer <- list()
    
    for (i in Images(object)) {
        cell_barcodes <- Seurat:::CellsByImage(object, images = i,
                                               unlist = TRUE)
        cells_obj_sub <- object[, cell_barcodes]
        images_sub_list <- list(object[[i]])
        names(images_sub_list) <- i
        cells_obj_sub@images <- images_sub_list
        if (!use_seurat_backend) {
            plot_list <- lapply(features,
                                function(feature) {
                                    max_color <- ifelse(feature == features[1],
                                                        bottom_right, top_left)
                                    SpatialFeaturePlot(object, feature,
                                                       images = i, pt.size.factor=pt.size.factor,# images=images
                                                       image.alpha = image.alpha,
                                                       stroke = stroke,
                                                       sfp_extra_arguments) +
                                        scale_fill_gradient(low = bottom_left,
                                                            high = max_color) +
                                        ggtitle(feature) +
                                        blend_plot_theme
                                })
            colors_list <- lapply(plot_list, extract_colors_from_ggplot)
            
            # Now construct the blended plot
            dat <- FetchData(cells_obj_sub, features)
            side_length <- 100
            col_grid <- gen_color_grid(side_length, bottom_left, bottom_right,
                                       top_left, top_right)
            dat_norm <- apply(dat, 2,
                              function(x) {
                                  round((side_length - 1) * x / max(x)) + 1
                              })
            colors_list[[3]] <- sapply(seq_len(nrow(dat_norm)),
                                       function(x) {
                                           col_grid[dat_norm[x, 1],
                                                    dat_norm[x, 2]]
                                       })
            legend_grid <- expand.grid(seq(from = min(dat[, features[1]]),
                                           to = max(dat[, features[1]]),
                                           length.out = side_length),
                                       seq(from = min(dat[, features[2]]),
                                           to = max(dat[, features[2]]),
                                           length.out = side_length))
            colnames(legend_grid) <- features
            legend_colors <- c(col_grid)
            legend_grid$color <- legend_colors
            names(legend_colors) <- legend_colors
            
            legend <- ggplot(legend_grid,
                             aes(x = .data[[features[1]]],
                                 y = .data[[features[2]]],
                                 color = color)) +
                geom_point(shape = 15, size = 1.9) +
                scale_color_manual(values = legend_colors) +
                coord_cartesian(expand = FALSE) +
                theme(legend.position = "none", aspect.ratio = 1,
                      panel.background = element_blank(),
                      axis.text.x = element_text(angle = 45,
                                                 hjust = 1)) +
                xlab(ifelse(is.null(feature_1_alt_name),
                            features[1], feature_1_alt_name)) +
                ylab(ifelse(is.null(feature_2_alt_name),
                            features[2], feature_2_alt_name))
        } else {
            if (top_right != "#FFFF00") {
                warning(paste("Cannot alter color in top right corner when",
                              "use_seurat_backend is TRUE"))
            }
            vis_reduc <- as.data.frame(cells_obj_sub@images[[i]]@boundaries$centroids@coords[, c(2, 1)])
            colnames(vis_reduc) <- c("vis_1", "vis_2")
            rownames(vis_reduc) <- colnames(object)
            vis_reduc$vis_2 <- -1 * vis_reduc$vis_2
            vis_reduc_mat <- as.matrix(vis_reduc)
            vis_reduc_obj <- CreateDimReducObject(embeddings = vis_reduc_mat,
                                                  key = "vis_")
            cells_obj_sub@reductions$vis <- vis_reduc_obj
            seurat_fp <- do.call(FeaturePlot, c(list(object = cells_obj_sub,
                                                     features = features,
                                                     reduction = "vis",
                                                     blend = TRUE,
                                                     cols = c(bottom_left,
                                                              bottom_right,
                                                              top_left),
                                                     combine = FALSE),
                                                fp_extra_arguments))
            colors_list <- lapply(seurat_fp[1:3], extract_colors_from_ggplot)
            legend <- seurat_fp[[4]]
        }
        
        names(colors_list) <- c(features, paste0(features[1], "_", features[2]))
        plot_list <- lapply(names(colors_list),
                            function(x) {
                                do.call(custom_color_SpatialDimPlot,
                                        c(list(cells_obj = cells_obj_sub, i,
                                               x, colors_list[[x]]),
                                          sfp_extra_arguments))
                            })
        
        plot_list[[4]] <- wrap_plots(ggplot() + theme_void(), legend,
                                     ggplot() + theme_void(), ncol = 1,
                                     heights = c(0.2, 0.6, 0.2))
        
        plot_list_outer[[i]] <- plot_list
    }
    
    if (combine == FALSE) {
        return(plot_list_outer)
    } else {
        plot_list_outer <- lapply(plot_list_outer,
                                  function(p) {
                                      wrap_plots(p, nrow = 1,
                                                 widths = c(0.28, 0.28,
                                                            0.28, 0.16))
                                  })
        p <- wrap_plots(plot_list_outer, ncol = 1)
        
        return(p)
    }
}


```






```{r ECs_Epithelial,fig.width=18,fig.height=5}

st.obj <- readRDS("../Rsave/st.obj2.Rds")
st.obj <- PrepSCTFindMarkers(st.obj, assay = "SCT")
st.obj <- NormalizeData(st.obj,assay = "Spatial")


EC_Arterial <- read.csv2("../Results/Theo/Top15_padj0.1/DGE_clusterEC_Lymphatic_byOrgan.csv",sep = ",")
EC_Arterial <- subset(EC_Arterial,gene %in% rownames(st.obj))


set1 <- c("ECSCR.1",
"GFAP",
"KIAA1462",
"PLP1",
"C1orf64")

set2 <- c("WT1", "GATA6", "ZFPM2", "TBX5", "PRDM6", "COLEC11", "GATA5", "RELN")

DefaultAssay(st.obj) <- "Spatial"

p1 <- SpatialFeaturePlot(st.obj,images = Images(st.obj)[5],features = subset(EC_Arterial,cluster== "Heart")$gene ,pt.size.factor = 3,ncol = 5,image.alpha = 0,stroke = 0.1)&theme(title = element_text(size = 10))&scale_fill_gradientn(colours = c("white","azure1" , "red1","red4"))&ggtitle("Heart markers")



p2 <- SpatialFeaturePlot(st.obj,images = Images(st.obj)[5],features = set2,pt.size.factor = 3,ncol = 5,image.alpha = 0,stroke = 0.1)&theme(title = element_text(size = 10))&scale_fill_gradientn(colours = c("white","azure1" , "red1","red4"))&ggtitle("ECs_Arterial-Heart markers")


DefaultAssay(st.obj) <- "integrated"
p3 <- FeatureScatter(st.obj,feature1 = "FGF23" ,feature2 =  "AFP",group.by = "integrated.sct_snn_res.0.1",cols = c("5"="yellow"))


Idents(st.obj) <- "integrated.sct_snn_res.0.1"
cells <- CellsByIdentities(st.obj, idents = c(5))

p4 <- SpatialDimPlot(st.obj,images = Images(st.obj)[2],pt.size.factor = 3,image.alpha = 0,stroke = 0.1,
  cells.highlight = cells[setdiff(names(cells), "NA")],
  cols.highlight = c("#FFFF00", "grey50"), facet.highlight = T, combine = T) + NoLegend()
p4



```



```{r,fig.width=50,fig.height=30}

DefaultAssay(st.obj) <- "SCT"
pdf("../Results/Manuscript/Spatial/CO.EXP.Heart_ECs_Arterial.pdf",width = 14,height = 9)
# Heart- ECs_Arterial
SpatialFeaturePlotBlend(
  subset(st.obj, orig.ident == unique(st.obj$orig.ident)[5]),
  features = c("MYL7", "TBX5"),image.alpha = 0.1,pt.size.factor = 2.5,stroke = NULL,
  use_seurat_backend = TRUE
)
dev.off()

# # Heart-EC_Lymphatic
# SpatialFeaturePlotBlend(
#   subset(st.obj, orig.ident == unique(st.obj$orig.ident)[1]),
#   features = c("MYL7", "MECOM"),image.alpha = 0.1,pt.size.factor = 3.5,
#   use_seurat_backend = TRUE
# )

pdf("../Results/Manuscript/Spatial/CO.EXP.Brain_ECs_Capilary_arterial.pdf",width = 14,height = 9)

# Brain-ECs_Capilary_arterial
# st.obj <- AddModuleScore(st.obj,features = list(c("PECAM1","ROR1")),name = "PECAM1_ROR1_")
# st.obj <- AddModuleScore(st.obj,features = list(c("FOXP2")),name = "FOXP2_")
SpatialFeaturePlotBlend(
  subset(st.obj, orig.ident == unique(st.obj$orig.ident)[2]),
  features = c("FOXP2","CDH11"),image.alpha = 0.1,pt.size.factor = 2.7,stroke = NULL,
  use_seurat_backend = TRUE
)
dev.off()

pdf("../Results/Manuscript/Spatial/CO.EXP.YolkSac_Mural_Pericytes.pdf",width = 14,height = 9)

# Yolk Sac-Mural_Pericytes
SpatialFeaturePlotBlend(
  subset(st.obj, orig.ident == unique(st.obj$orig.ident)[2]),
  features = c("APOA1","VTN"),image.alpha = 0.1,pt.size.factor = 2.7,stroke = NULL,
  use_seurat_backend = TRUE
)
dev.off()

pdf("../Results/Manuscript/Spatial/CO.EXP.Liver_Mural_Fibroblasts.1.pdf",width = 14,height = 9)

# Liver Mural_Fibroblasts.1
SpatialFeaturePlotBlend(
  subset(st.obj, orig.ident == unique(st.obj$orig.ident)[5]),
  features = c("PLAC1","BCAM"),image.alpha = 0.1,pt.size.factor = 2.5,stroke = NULL,
  use_seurat_backend = TRUE
)  #PAx2 is a shared marker between vasculature and Kidney data

dev.off()



```


# Conserved markers

```{r,fig.width=50,fig.height=30}

ConservedMarkers <- read.csv("../Results/Theo/ConservedMarkers_BrainHead_Heart_vsAllOrgans__GLOBAL.csv")

top <- ConservedMarkers[order(
  -ConservedMarkers$Brain.Head_avg_log2FC,
  -ConservedMarkers$Heart_avg_log2FC
), ][1:200,]

top.select <- subset(top,gene %in% intersect(rownames(st.obj),top$gene)&Heart_avg_log2FC>2 &Brain.Head_avg_log2FC>2)
top.select

down <- ConservedMarkers[order(
  -ConservedMarkers$Brain.Head_avg_log2FC,
  -ConservedMarkers$Heart_avg_log2FC
), ][(dim(ConservedMarkers)[1]-300):dim(ConservedMarkers)[1],]


down.select <- subset(down,gene %in% intersect(rownames(st.obj),down$gene) & Heart_avg_log2FC < -2 & Brain.Head_avg_log2FC < -2)


pdf("../Results/Manuscript/Spatial/Consereved.B&H.pdf",width = 25,height = 15)

SpatialFeaturePlot(st.obj,images = Images(st.obj)[7],features = top.select$gene ,pt.size.factor = 3,ncol = 7,image.alpha = 0,stroke = 0.1)&theme(title = element_text(size = 30))&scale_fill_gradientn(colours = c("white","azure1" , "red1","red4"))&ggtitle("B&H")
dev.off()

pdf("../Results/Manuscript/Spatial/Consereved.B&H.AC099489.1.pdf",width = 25,height = 15)

SpatialFeaturePlot(st.obj,features = "SLC35F1" ,pt.size.factor = 3,ncol = 7,image.alpha = 0,stroke = 0.1)&theme(title = element_text(size = 30))&scale_fill_gradientn(colours = c("white","azure1" , "red1","red4"))&ggtitle("B&H")
dev.off()

```


```{r clustering,fig.width=20,fig.height=20}

Semla <- readRDS("../Data/Visium/whole_embr_selected_sections_harmony_clust_deg.rds")
st.obj <- subset(st.obj,slide_id %in% unique(Semla$slide_id))
head(Semla@meta.data)

head(st.obj@meta.data)

st.obj <-subset(st.obj,slide_id %in% unique(Semla$slide_id)) 

st.obj$unified_barcode <- paste(substr(colnames(st.obj), 1, 16),st.obj$slide_id,sep = "_")
Semla$unified_barcode <- paste(substr(colnames(Semla), 1, 16),Semla$slide_id,sep = "_")

st.obj@meta.data[match(Semla$unified_barcode,st.obj$unified_barcode),]

st.obj$Semla.check <- ifelse(st.obj$unified_barcode%in%Semla$unified_barcode,"Include","Exclude")
Semla$Semla.check <- ifelse(Semla$unified_barcode%in%st.obj$unified_barcode,"Include","Exclude")

Semla <- subset(Semla,slide_id %in% unique(Semla$slide_id)[-c(1,3,4)])
st.obj <- subset(st.obj,slide_id %in% unique(Semla$slide_id))


st.obj@meta.data[,37:40] <- Semla@meta.data[match(st.obj$unified_barcode,Semla$unified_barcode),c(10:13)]


st.obj <- SetIdent(st.obj,value = "seurat_clusters_harmony")

st.obj <- RenameIdents(
  st.obj,
  "0"  = "Cranial neural crest cells",
  "1"  = "Proliferative NSCs",
  "2"  = "Posterior ventral mesenchyme",
  "3"  = "Posterior ventral mesenchyme",
  "4"  = "Paraxial mesoderm",
  "5"  = "Immature neurons",
  "6"  = "Ventricular zone radial glial cells",
  "7"  = "Myocardium",
  "8"  = "Umbilical cord / connecting-stalk",
  "9"  = "Secretory yolk-sac endoderm",
  "10" = "Anterior cranio-pharyngeal epithelium (optic–thyroid field)",
  "11" = "Liver hepatoblasts",
  "12" = "S-phase progenitors",
  "13" = "Erythrocyte lineage",
  "14" = "Secretory yolk-sac endoderm",
  "15" = "Extra-embryonic mesenchyme",
  "16" = "Hindgut/cloacal splanchnic mesenchyme",
  "17" = "Peripheral sensory lineage",
  "18" = "Gut tube epithelium",
  "19" = "Pharyngeal arch",
  "20" = "Ventral mesenchyme",
  "21" = "Floor plate progenitors",
  "22" = "Skeletal muscle",
  "23" = "Cranial mesenchyme",
  "24" = "Peripheral sensory lineage"
)

st.obj$Annotation <- Idents(st.obj)
 
cols <- c(
  "Posterior ventral mesenchyme"                 = "#D55E00",
  "Ventral mesenchyme"                           = "#E69F00",
  "Paraxial mesoderm"                            = "#B5651D",
  "Cranial mesenchyme"                           = "#A0522D",
  "Extra-embryonic mesenchyme"                   = "#CC7722",
  "Pharyngeal arch"                              = "#FF8C00",
  "Hindgut/cloacal splanchnic mesenchyme"        = "#B7410E",
  "Skeletal muscle"                              = "#964B00",
  "Myocardium"                                   = "#8B4513",
  "Umbilical cord / connecting-stalk"            = "#CD853F",

  "Liver hepatoblasts"                           = "#66A61E",
  "Secretory yolk-sac endoderm"                  = "#1B9E77",
  "Gut tube epithelium"                          = "#4DAF4A",
  "Anterior cranio-pharyngeal epithelium (optic–thyroid field)" = "#A6D854",

  "Immature neurons"                             = "#377EB8",
  "Ventricular zone radial glial cells"          = "#4A4FAA",
  "Proliferative NSCs"                           = "#984EA3",
  "Peripheral sensory lineage"                   = "#6A3D9A",
  "Floor plate progenitors"                      = "#7B68EE",

  "Cranial neural crest cells"                   = "#20B2AA",
  "Erythrocyte lineage"                          = "#A50F15"
)
 

  
  p <-SpatialDimPlot(st.obj,cols = cols,group.by = "Annotation",images = Images(st.obj)[c(3,1)],pt.size.factor = 2.5,image.alpha  = .5,ncol = 2)&NoLegend()

  p[[1]] <- p[[1]] + ggtitle("CS13")
p[[2]] <- p[[2]] + ggtitle("CS15")
  # build legend separately
lg <- SpatialDimPlot(
  st.obj,
  cols = cols,
  group.by = "Annotation"
) + theme(legend.position = "right")

legend <- cowplot::get_legend(lg)

# remove legend from main plot
p_nolegend <- p + theme(legend.position="none")


pdf("../Results/Manuscript/Spatial/Fig1.pdf",width = 12,height = 7)

# arrange
plot_grid(
  p_nolegend,
  legend,
  ncol = 2,
  rel_widths = c(4, 1.5)
)

dev.off()  



DEG <- FindAllMarkers(st.obj,group.by = "Annotation",assay = "SCT",only.pos = T,logfc.threshold = 0.4)

top5 <- c()
for (clusters in unique(DEG$cluster)) {
  x <- subset(DEG, cluster == clusters )
  x <- x[order(-x$avg_log2FC, -x$p_val_adj),][1:5,]
  top5 <- rbind(top5,x)
}


pdf("../Results/Manuscript/Spatial/Extended.Fig1.pdf",width = 20,height = 6.5)

 DotPlot(st.obj,
                 #selecting top30 genes for the dotplot
                 features = unique(top5$gene)
,assay = "SCT",scale.by = "size")+ggtitle("Celltype gene signatures")+theme_bw()+rotate_x_text(90)+scale_color_gradient2(low = "navyblue",mid = "white",high = "red")+theme(axis.text = element_text(face = "bold"))
dev.off()


# st.obj <- SCTransform(st.obj,assay = "Spatial")


p <- VlnPlot(st.obj,features = "PECAM1",group.by = "Annotation",pt.size = 0,assay = "SCT",cols = cols)+rotate_x_text(70)+NoLegend()


pdf("../Results/Manuscript/Spatial/Fig6_CD31.vlnPlot.pdf",width = 10,height = 8)
VlnPlot(st.obj,features = "PECAM1",group.by = "Annotation",pt.size = 0,assay = "SCT",cols = cols)+rotate_x_text(70)+NoLegend()
dev.off()


saveRDS(st.obj,"../Rsave/st.obj3.Rds")

```



```{r clustering,fig.width=20,fig.height=20}

st.obj <- readRDS("../Rsave/st.obj3.Rds")
DefaultAssay(st.obj) <- "Spatial"
st.obj <- AddModuleScore(st.obj,features = list(c("ABCB1","CDH6","SV2C","AJAP1","CHGA")),name = "cECs_Brain.score")
st.obj <- AddModuleScore(st.obj,features = list(c("ADAMTSL3","CCL21","AQP1","TNNI3","GATA4","CSRP3","FGF23","TNNT3","IL1RL1","CRHBP","FABP5","MEOX2","MB","INMT","OIT3","LPL","MICAL2")),name = "cECs_Heart.score")
st.obj <- AddModuleScore(st.obj,features = list(c("FOXQ1","ZIC1","SRARP","ZIC2","CCK","C20orf85","LRP2","SLC38A11","IGFBPL1")),name = "mPrecursors_Brain.score")
st.obj <- AddModuleScore(st.obj,features = list(c("CCL21","PLA2G2A","IL33","PLA2G5","TBX5","COL6A6","TBX20","WT1","GATA4","MYL4","PI15","SCN7A","NRK","PDLIM3")),name = "mPrecursors_Heart.score")
st.obj <- AddModuleScore(st.obj,features = list(c("AL162718.1","ARHGEF28")),name = "cECs_Brain_Heart.score")
st.obj <- AddModuleScore(st.obj,features = list(c("BRINP3")),name = "mPrecursors_Brain_Heart.score")


colnames(st.obj@meta.data)[c(42:47)] <- gsub("score1","Score",colnames(st.obj@meta.data[c(42:47)]))

# st.obj@meta.data <- st.obj@meta.data[-c(42:47)]


p1_1 <- SpatialFeaturePlot(st.obj,features = "cECs_Brain.Score",ncol = 3,image.alpha = .2,pt.size.factor = 3)
p2_1 <- SpatialFeaturePlot(st.obj,features = "cECs_Heart.Score",ncol = 3,image.alpha = .2,pt.size.factor = 3)
p3_1 <- SpatialFeaturePlot(st.obj,features = "mPrecursors_Brain.Score",ncol = 3,image.alpha = .2,pt.size.factor = 3)
p4_1 <- SpatialFeaturePlot(st.obj,features = "mPrecursors_Heart.Score",ncol = 3,image.alpha = .2,pt.size.factor = 3)

pdf("../Results/Manuscript/Spatial/cECs_Brain.score1.pdf",width = 10,height = 10)
p1_1
dev.off()

pdf("../Results/Manuscript/Spatial/cECs_Heart.score1.pdf",width = 10,height = 10)
p2_1
dev.off()

pdf("../Results/Manuscript/Spatial/mPrecursors_Brain.score1.pdf",width = 10,height = 10)
p3_1
dev.off()

pdf("../Results/Manuscript/Spatial/mPrecursors_Heart.score1.pdf",width = 10,height = 10)
p4_1
dev.off()


p5_1 <- SpatialFeaturePlot(st.obj,features = "cECs_Brain_Heart.score1",ncol = 3,image.alpha = .2,pt.size.factor = 3)
p5_2 <- SpatialFeaturePlot(st.obj,features = "mPrecursors_Brain_Heart.score1",ncol = 3,image.alpha = .2,pt.size.factor = 3)


p1_2 <- VlnPlot(st.obj,group.by ="Annotation",features = "cECs_Brain.score1",cols = cols,pt.size = 0)&NoLegend()+rotate_x_text(80)+theme(axis.text.x =element_text(size = 0))

p2_2 <- VlnPlot(st.obj,group.by ="Annotation",features = "cECs_Heart.score1",cols = cols,pt.size = 0)&NoLegend()+rotate_x_text(80)
p3_2 <- VlnPlot(st.obj,group.by ="Annotation",features = "mPrecursors_Brain.score1",cols = cols,pt.size = 0)&NoLegend()+rotate_x_text(80)
p4_2 <- VlnPlot(st.obj,group.by ="Annotation",features = "mPrecursors_Heart.score1",cols = cols,pt.size = 0)&NoLegend()+rotate_x_text(80)


cols <- c(
  "Posterior ventral mesenchyme"                 = "grey",
  "Ventral mesenchyme"                           = "grey",
  "Paraxial mesoderm"                            = "grey",
  "Cranial mesenchyme"                           = "#A0522D",
  "Extra-embryonic mesenchyme"                   = "#CC7722",
  "Pharyngeal arch"                              = "#FF8C00",
  "Hindgut/cloacal splanchnic mesenchyme"        = "#B7410E",
  "Skeletal muscle"                              = "#964B00",
  "Myocardium"                                   = "#8B4513", #
  "Umbilical cord / connecting-stalk"            = "#CD853F",

  "Liver hepatoblasts"                           = "#66A61E",
  "Secretory yolk-sac endoderm"                  = "#1B9E77",
  "Gut tube epithelium"                          = "#4DAF4A",
  "Anterior cranio-pharyngeal epithelium (optic–thyroid field)" = "#A6D854",

  "Immature neurons"                             = "#377EB8", #
  "Ventricular zone radial glial cells"          = "#4A4FAA", #
  "Proliferative NSCs"                           = "#984EA3",
  "Peripheral sensory lineage"                   = "#6A3D9A", #
  "Floor plate progenitors"                      = "#7B68EE", #

  "Cranial neural crest cells"                   = "#20B2AA",  #
  "Erythrocyte lineage"                          = "#A50F15"
)

SpatialDimPlot(st.obj,group.by ="Annotation",ncol = 3,image.alpha = .2,pt.size.factor = 3,cols = cols)&NoLegend()



## Ploting the Fig5A enriched pathways in brain and heart

p1 <- SpatialFeaturePlot(st.obj,features = "FGF23",ncol = 1,image.alpha = .2,pt.size.factor = 3)&ggtitle("")

p1[[1]] <- p1[[1]]+ggtitle("FGF pathway (Ligand)")

p2 <- SpatialFeaturePlot(st.obj,features = "FGFR1",ncol = 1,image.alpha = .2,pt.size.factor = 3)&ggtitle("")

p2[[1]] <- p2[[1]]+ggtitle("FGF pathway (Receptor)")

p1_final <- p1|p2


p1 <- SpatialFeaturePlot(st.obj,features = "CD55",ncol = 1,image.alpha = .2,pt.size.factor = 3)&ggtitle("")

p1[[1]] <- p1[[1]]+ggtitle("ADGRE pathway (Ligand)")

p2 <- SpatialFeaturePlot(st.obj,features = "ADGRE5",ncol = 1,image.alpha = .2,pt.size.factor = 3)&ggtitle("")

p2[[1]] <- p2[[1]]+ggtitle("ADGRE pathway (Receptor)")

p2_final <- p1|p2



p1 <- SpatialFeaturePlot(st.obj,features = "APOA1",ncol = 1,image.alpha = .2,pt.size.factor = 3)&ggtitle("")

p1[[1]] <- p1[[1]]+ggtitle("ApoA pathway (Ligand)")

p2 <- SpatialFeaturePlot(st.obj,features = "ABCA1",ncol = 1,image.alpha = .2,pt.size.factor = 3)&ggtitle("")

p2[[1]] <- p2[[1]]+ggtitle("ApoA pathway (Receptor)")

p3_final <- p1|p2



pdf("../Results/Manuscript/Figure5/Heart_Spatial_L_R.pdf",height = 20,width = 20)
wrap_plots(p1_final,p3_final,p2_final,ncol = 3)
dev.off()



p1 <- SpatialFeaturePlot(st.obj,features = "HSPG2",ncol = 1,image.alpha = .2,pt.size.factor = 3)&ggtitle("")

p1[[1]] <- p1[[1]]+ggtitle("HSPG pathway (Ligand)")

p2 <- SpatialFeaturePlot(st.obj,features = "DAG1",ncol = 1,image.alpha = .2,pt.size.factor = 3)&ggtitle("")

p2[[1]] <- p2[[1]]+ggtitle("HSPG pathway (Receptor)")

p1_final <- p1|p2

p2_final <- SpatialFeaturePlot(st.obj,features = "PCDHGC3",ncol = 1,image.alpha = .2,pt.size.factor = 3)&ggtitle("")

p2_final[[1]] <- p2_final[[1]]+ggtitle("PCDH pathway (Ligand&receptor)")


p3_final <- SpatialFeaturePlot(st.obj,features = "CLDN11",ncol = 1,image.alpha = .2,pt.size.factor = 3)&ggtitle("")

p3_final[[1]] <- p3_final[[1]]+ggtitle("CLDN pathway (Ligand&receptor)")



p1 <- SpatialFeaturePlot(st.obj,features = "CD34",ncol = 1,image.alpha = .2,pt.size.factor = 3)&ggtitle("")

p1[[1]] <- p1[[1]]+ggtitle("CD34 pathway (Ligand)")

p2 <- SpatialFeaturePlot(st.obj,features = "SELP",ncol = 1,image.alpha = .2,pt.size.factor = 3)&ggtitle("")

p2[[1]] <- p2[[1]]+ggtitle("CD34 pathway (Receptor)")

p4_final <- p1|p2


p1 <- SpatialFeaturePlot(st.obj,features = "SLC1A3",ncol = 1,image.alpha = .2,pt.size.factor = 3)&ggtitle("")

p1[[1]] <- p1[[1]]+ggtitle("Glutamate pathway (Ligand)")

p2 <- SpatialFeaturePlot(st.obj,features = "GRM3",ncol = 1,image.alpha = .2,pt.size.factor = 3)&ggtitle("")

p2[[1]] <- p2[[1]]+ggtitle("Glutamate pathway (Receptor)")

p5_final <- p1|p2


pdf("../Results/Manuscript/Figure5/Brain_Spatial_L_R.pdf",height = 20,width = 30)
wrap_plots(p1_final,p2_final,p3_final,p4_final,p5_final,ncol = 5)
dev.off()

```
